feat: iac test terraform support
snyk/snyk pull request #1412
Opened 2020-09-15 10:45 UTC by rontalx

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2020-09-17 14:42 UTC, gitphill commented on src/lib/iac/iac-parser.ts
> +    qs: assembleQueryString({}),
is this required?

2020-09-17 14:53 UTC, rontalx commented on src/lib/iac/iac-parser.ts
> +    qs: assembleQueryString({}),
nope, left-overs from local debugging.
Removed 👍

2020-09-17 14:58 UTC, gitphill approved these changes

2020-09-17 15:12 UTC, Shesekino approved these changes
looks good to me :)
left some comments/questions, address them however you like, nothing critical.

2020-09-18 12:20 UTC, almog27 commented on src/lib/iac/constants.ts
> +export type IacProjectTypes = 'k8sconfig' | 'helmconfig' | 'terraformconfig';
We should only add here CLI supported project types

2020-09-18 12:36 UTC, almog27 commented on src/lib/detect.ts
> +      } = await makeValidateTerraformRequest(fileContent);
Why not keep it same behaviour as `validateK8sFile`

2020-09-18 13:08 UTC, almog27 commented on src/lib/iac/constants.ts
> +export enum IacProjectType {
I see that there are currently two "conventions" in the repo - `All caps` (as we saw in other repos as well) - and `all lower`.
Let's stick with the `all caps`.

2020-09-18 22:30 UTC, almog27 commented on src/lib/iac/constants.ts
> +  tf: IacProjectType.Terraform,
What about `json`?

2020-09-21 07:35 UTC, rontalx commented on src/lib/iac/iac-parser.ts
> +import request = require('./../request');
Yeah I agree.
There was this weird importing error for both of these packages when importing them using import/from.
![image](https://user-images.githubusercontent.com/43777855/93491280-33ae2600-f912-11ea-87d2-5dd708dfce55.png)
So for now took this (bad) example from others that have required these modules in the same way.

2020-09-21 08:53 UTC, Shesekino commented on src/lib/iac/iac-parser.ts
> +import snyk = require('../.');
I'm not familiar enough with the code base to give a good answer here 😦
mostly raising this concern because of the comment I linked - if you think it's fine then probably nothing to worry about.

otherwise I'd probably see how I could untangle the env var from that module

2020-09-21 08:55 UTC, Shesekino commented on src/lib/iac/iac-parser.ts
> +import request = require('./../request');
are these errors only in the IDE or elsewhere as well? maybe something is funky with the Node version it thinks it's running https://github.com/mirumee/saleor/issues/3716

2020-09-21 10:13 UTC, JackuB requested changes
Left some comments. 
Also, in general, with so many changes in iac test path and interfaces, I'm surprised that there are no unit/acceptance tests that needs updating?

👍 on new smoke tests - you will also have to update mounted fixtures in dockerfile for Alpine test here https://github.com/snyk/snyk/blob/0a0193fd7699d8f25156e5cae22700a81a063c36/test/smoke/alpine/Dockerfile#L4-L5

2020-09-21 10:13 UTC, JackuB commented on test/fixtures/iac-terraform/sg_open_ssh.tf
> +resource "aws_security_group" "allow_ssh" {
You might want to add these to the CODEOWNERS

2020-09-21 10:13 UTC, JackuB commented on src/lib/iac/iac-parser.ts
> +      Authorization: `token ${snyk.api}`,
You should use https://github.com/snyk/snyk/blob/0a0193fd7699d8f25156e5cae22700a81a063c36/src/lib/api-token.ts#L6-L9 to avoid self-require

2020-09-21 12:39 UTC, JackuB commented on test/smoke/spec/snyk_test_iac_spec.sh
> +    It "outputs the expected text when running with --sarif flag"
Sarif output should be a valid JSON right? Might be worth to add additional check for it as well:

https://github.com/snyk/snyk/blob/0a0193fd7699d8f25156e5cae22700a81a063c36/test/smoke/spec/snyk_test_spec.sh#L77

2020-09-21 13:59 UTC, almog27 approved these changes

2020-09-21 14:27 UTC, JackuB approved these changes

2020-09-21 17:00 UTC, merged

2020-09-21 17:05 UTC, snyksec commented
:tada: This PR is included in version 1.399.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk/v/1.399.0)
- [GitHub release](https://github.com/snyk/snyk/releases/tag/v1.399.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: