feat: iac test directory support
snyk/snyk pull request #1430
Opened 2020-09-29 12:01 UTC by almog27

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
This PR adds Directory support for `snyk iac test`.
Before this PR, only a single file was supported. This PR enables us also to scan a directory of IaC files (with various IaC types) and get their result in a similar way that `--all-projects` is working on.

Small note - we will need to merge this after #1421 will be merged - however it will not affect the functionality of this PR.

#### How should this be manually tested?
This PR using the Smoke tests functionality.

#### Screenshots
![Screen Shot 2020-09-29 at 13 59 58](https://user-images.githubusercontent.com/1466549/94553126-af886680-0260-11eb-9cf2-6de60d295a5c.png)

#### Additional questions

2020-09-29 12:59 UTC, almog27 commented on src/lib/detect-iac.ts
> +import * as fs from 'fs';
In this file, we separated the IaC `detect` functionality from the rest of the `detect` functionality.
Most of the code here was moved from `src/lib/detect.ts` file

2020-09-30 15:12 UTC, JackuB requested changes
We are too worried about this PR not updating any tests. We would like to see new Jest tests for the new behavior - e.g. detect-iac methods and something to check the return types.

Also CI tests are still failing on cli-args test 🙏

2020-09-30 18:29 UTC, almog27 commented
> We are too worried about this PR not updating any tests. We would like to see new Jest tests for the new behavior - e.g. detect-iac methods and something to check the return types.
> 
> Also CI tests are still failing on cli-args test 🙏

@JackuB , Yes, you are right there are some tests that needed to be edited that causing the CI tests to fail.
Will update them after the other pr will be merged.

Regarding the jest test - as the Terraform, it more complicated to use the Jest but will check it again

2020-10-01 11:13 UTC, rontalx reviewed
we're really forcing this code-path to work for directories...
if this isn't useful from a product perspective, following our discussion, let's see if we can hack it to work with full recursive directory scanning.

2020-10-15 10:05 UTC, rontalx approved these changes
Approving this just because we are tight on schedule with this feature.
Following our recent team discussions on the CLI refactor and our Tech-Roadmap, this PR marks a point where we stop adding new functionality to the CLI until we properly refactor our logic - as it's no longer reasonably maintainable, testable, and sustainable.
cc: @JackuB

2020-10-15 15:08 UTC, JackuB commented
<img width="836" alt="Screenshot 2020-10-15 at 17 05 27" src="https://user-images.githubusercontent.com/1788727/96148533-a2c66c80-0f08-11eb-9fdb-384658a834bd.png">

Ran into a small issue with error not being returned correctly `NotSupportedIacFileError is not a constructor`
When running `node ./dist/cli/index.js iac test ./test/fixtures/iac/terraform/ --all-projects` locally. Maybe it's not exported properly?

2020-10-15 15:14 UTC, JackuB approved these changes
Small issue with --all-projects is not blocking, as it's an unsupported flag combination.

Please squash or rename the commits (see Danger message) so it follows contributing guidelines https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md#commit-messages so that our Release notes make sense https://github.com/snyk/snyk/releases

2020-10-18 08:19 UTC, merged

2020-10-18 08:22 UTC, snyksec commented
:tada: This PR is included in version 1.415.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk/v/1.415.0)
- [GitHub release](https://github.com/snyk/snyk/releases/tag/v1.415.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: