feat: analytics- enable getting a command version
snyk/snyk pull request #1552
Opened 2020-12-02 16:19 UTC by Avishagp

#### What does this PR do?
Enable getting a command's version and checking if a software is installed on user's machine.

#### What are the relevant tickets?
https://snyksec.atlassian.net/browse/HAMMER-186

2020-12-03 10:52 UTC, JackuB requested changes
I'd like to see a test that verifies the analytics object contains the `environment.npmVersion` with a valid semver

2020-12-09 16:23 UTC, JackuB requested changes
Some questions/suggestions - one blocking comment around the standalone

2020-12-09 16:23 UTC, JackuB commented on src/lib/analytics-sources.ts
> +        console.warn(error);
Wondering whether this should log only in debug mode - especially since it'll only affected the analytics module

2020-12-09 16:23 UTC, JackuB commented on test/analytics.spec.ts
> +      fail('analytics creation failed!');
Wouldn't the `await analytics` call throw in this case? Rather than returning `falsy` value?

`analytics()` returns a Promise, so if the Promise would `reject`, then it would also kill this test, no?

2020-12-09 16:23 UTC, JackuB commented on test/analytics.spec.ts
> +    expect(vals).toContain('__test__');
What is this test proving? `data` is something created few lines above?

2020-12-09 16:23 UTC, JackuB commented on src/lib/analytics.js
> +      if (isStandalone) {
```suggestion
      if (!isStandalone) {
```

We should check the opposite - in standalone mode we ship (and control) node/npm version. We care about the non-standalone ones.

Check whether it affects logic in any test as well 🤞

2020-12-10 08:13 UTC, Avishagp commented on test/analytics.spec.ts
> +    expect(vals).toContain('__test__');
Data is changed during analytics creation. This test checks if the original values given weren't changed

2020-12-10 08:50 UTC, JackuB approved these changes

2020-12-10 09:41 UTC, merged

2020-12-10 09:47 UTC, snyksec commented
:tada: This PR is included in version 1.435.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk/v/1.435.0)
- [GitHub release](https://github.com/snyk/snyk/releases/tag/v1.435.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: