feat: Add impact and resolve fields in sarif output.
snyk/snyk pull request #1558
Opened 2020-12-07 15:52 UTC by ipapast

CC-517

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2020-12-07 18:31 UTC, almog27 commented on src/lib/snyk-test/iac-test-result.ts
> +    impact: string;
We don't want to present the issue too?
I think even if we don't intend to present it in this case - it will be better to add it here and remove the description.

2020-12-07 18:32 UTC, almog27 commented on test/acceptance/cli-test/iac/cli-test.iac-utils.ts
> +    iacDescription: { impact: '', resolve: '' },
Same here

2020-12-10 18:04 UTC, ipapast commented on src/lib/snyk-test/iac-test-result.ts
> +    impact: string;
Issue is slightly different than the shortDescription. I am not sure which one is more valuable as a piece of information, they both give a similar phrase more or less in different words. 

❓ What's the difference in adding it here? Just to have the same object fields in iacDescription?

❗ Some examples: 
- shortDescription: "Container could be running with outdated image"
- iacDescription.issue: "The image policy does not prevent image reuse"

- shortDescription: "Container is running without AppArmor profile"
- iacDescription.issue: "The AppArmor profile is not set correctly"

2020-12-11 11:26 UTC, aron requested changes
This is fantastic, I think now seeing the output in the GitHub UI, the description isn't the best place for the impact.

The help field where we show the resolution looks like a better spot to put all of this information and describe to the user the issue, impact and resolution as we do in the Snyk UI.

What do you think?

2020-12-11 11:26 UTC, aron commented on src/lib/snyk-test/iac-test-result.ts
> +    impact: string;
>❓ What's the difference in adding it here? Just to have the same object fields in iacDescription?

Exactly. 👍 for adding it to the type definition for completeness. This should represent the object we're having returned from the API even if we don't use it here.

> I am not sure which one is more valuable as a piece of information, they both give a similar phrase more or less in different words.

I think it's largely based on this piece of UI. So I would imagine the issue is intended to be displayed with the impact and resolution.

![image](https://user-images.githubusercontent.com/47144/101897270-34b5c300-3ba2-11eb-845b-5b30f04b4560.png)

2020-12-11 11:26 UTC, aron commented on src/cli/commands/test/iac-output.ts
> +        text: `Type: ${iacTypeToText[issue.type]} ${issue.subType}, impact: ${
I think seeing this in context within the screenshot, it might not make sense to put this here. This "full description" doesn't really have much space.

Instead how about we extend the markdown in the help text to mimic the Snyk UI (e.g. in the screenshot below).

```ts
`
**The issue is...** 
${issue.iacDescription.issue}

**The impact of this is...**
${issue.iacDescription.impact}

**You can resolve this by...**
${issue.iacDescription.resolve}
`
```

---

**The issue is...** 
The image policy does not prevent image reuse

**The impact of this is...**
Blah blah blah.

**You can resolve this by...**
Adding foo to the bar.

2020-12-11 16:41 UTC, ipapast commented on src/cli/commands/test/iac-output.ts
> +        text: `Type: ${iacTypeToText[issue.type]} ${issue.subType}, impact: ${
![image](https://user-images.githubusercontent.com/6989529/101930190-bbcd6000-3bcf-11eb-9653-a5e40da3f68f.png)

2020-12-11 16:46 UTC, ipapast commented on src/cli/commands/test/iac-output.ts
> +        text: `Type: ${iacTypeToText[issue.type]} ${issue.subType}, impact: ${
The changes now reflect the Snyk UI too.
You can see it also in my test repo https://github.com/ipapast/k8-test/security/code-scanning

2020-12-11 17:03 UTC, aron approved these changes
Nice, looks fantastic. I think it might be easier to keep the nice template literals but to trim the leading whitespace from each line with a `replace()` function.

2020-12-11 17:03 UTC, aron commented on src/cli/commands/test/iac-output.ts
> +        ${issue.iacDescription.resolve}`,
We're going to have the same issue here as we had with the markdown. The string is going to look like:

```
The issue is...
        ${issue.iacDescription.issue}

        The impact of this is...
        ${issue.iacDescription.impact}
        
        You can resolve this by...
        ${issue.iacDescription.resolve}
```

2020-12-11 22:20 UTC, ipapast commented on src/cli/commands/test/iac-output.ts
> +        ${issue.iacDescription.resolve}`,
Correct me if I'm wrong, but my understanding is, that if the markdown field exists, then the sarif output will display that.
The text field is only mandatory if the markdown field does not exist. In this case, I think we can even have an empty string as a text field and the output would still be the same.
In summary, I think the best thing is to do is to display text: ' ' and then markdown as we have already formmated it.

2020-12-14 10:00 UTC, aron commented on src/cli/commands/test/iac-output.ts
> +        ${issue.iacDescription.resolve}`,
As you have it is absolutely fine, we want both as it means that the content can be output anywhere as plaintext but also enhanced as markdown if the client understands it. All I meant by my comment was that the plain text version is going to be indented after the first line. Imagine if this Sarif file was printed by a command line tool as plain text to the terminal, it would look odd if the first line of subsequent sections were indented.

Lets chat if this still doesn't make sense :)

2020-12-14 10:13 UTC, ipapast commented on src/cli/commands/test/iac-output.ts
> +        ${issue.iacDescription.resolve}`,
Sorry for the back and forth - I was talking for the specific purposes of Github Security display and you were talking about the case of the plain output. I get you now :) I'll do that change now

2020-12-14 10:16 UTC, almog27 commented on src/lib/snyk-test/iac-test-result.ts
> +    impact: string;
The `description` is the old field that we should remove soon.
We split the description into 3 fields - `issue`, `impact` and `resolve` which we put under those under the iacDescription

2020-12-14 10:17 UTC, almog27 approved these changes

2020-12-14 13:42 UTC, ipapast commented on src/cli/commands/test/iac-output.ts
> +        ${issue.iacDescription.resolve}`,
Updated the original PR comment with the most updated screenshots for any future reference.
Added a replace function to the help fields.
Squashed the commits and will merge as soon as the checks passed.

2020-12-14 14:50 UTC, merged

2020-12-14 14:58 UTC, snyksec commented
:tada: This PR is included in version 1.437.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/snyk/v/1.437.0)
- [GitHub release](https://github.com/snyk/snyk/releases/tag/v1.437.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: