fix: iac k8s validation helm file
snyk/snyk pull request #1584
Opened 2021-01-17 13:17 UTC by almog27

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
This PR fixes the fact the for k8s files `iac test` is not doing helm validation and fail on internal error instead of showing a proper message that indicates this file type is not supported.

#### Any background context you want to provide?
As part of an investigation that happens in Cloud Config team, we understood that in the UI we have validation for Helm files as part of the k8s file scanning, while in the CLI there is no such validation.
This PR align between those

2021-01-18 09:00 UTC, p0tr3c commented on src/lib/iac/iac-parser.ts
> +  return fileContent.includes('{{');
This is not enough to identify file as only helm.
if `{{` is used outside of quotes or string literals then this is fine.
But for configMaps these characters may be included as part of configuration file for a service.

2021-01-20 08:13 UTC, p0tr3c approved these changes

2021-01-21 10:09 UTC, JackuB requested changes
Let's swap the dependency 👍

2021-01-21 10:09 UTC, JackuB commented on package.json
> +    "yamljs": "^0.3.0"
We already have a different yaml parsing library in the snyk/policy package: https://github.com/snyk/policy/blob/master/package.json#L30

2021-01-21 10:09 UTC, JackuB commented on src/lib/iac/iac-parser.ts
> +export function isInvalidYaml(filePath: string, fileContent: string) {
Wouldn't it make sense to have the check be the opposite: `isValidYaml`?

2021-01-21 10:10 UTC, almog27 commented on package.json
> +    "yamljs": "^0.3.0"
The `js-yaml` library does not do the required validation, but a parsing to JSON

2021-01-21 11:13 UTC, JackuB commented on package.json
> +    "yamljs": "^0.3.0"
Calling a safeLoad function from it will validate it, no?

2021-01-21 12:13 UTC, almog27 commented on package.json
> +    "yamljs": "^0.3.0"
@JackuB I checked the posibility to use it instead, while js-yaml parse well multiple docs, yamljs only return the first one.
And yamljs do the validation while js-yaml not.
So we need both of them.

2021-01-21 15:06 UTC, JackuB commented on package.json
> +    "yamljs": "^0.3.0"
Got some examples of those invalid docs? 🤔

2021-01-21 19:58 UTC, almog27 commented on package.json
> +    "yamljs": "^0.3.0"
On the `js-yaml` it writes on the load 

> NOTE: JS-YAML does not support schema-specific tag resolution restrictions. So, the JSON schema is not as strictly defined in the YAML specification. It allows numbers in any notation, use Null and NULL as null, etc. The core schema also has no such restrictions. It allows binary notation for integers.
https://github.com/nodeca/js-yaml#load-string---options-

As a result - when it finds invalid it changes it to null and not throw an error

`yamljs` readme only talks on a single yaml file an not talking on multidoc yaml.
However - I did tested it locally - and it only return the first one.
https://github.com/jeremyfa/yaml.js#readme

2021-02-10 10:36 UTC, almog27 commented
Closing this PR till further investigation

2021-02-10 10:36 UTC, closed without merging