chore: update critical sev colour
snyk/snyk pull request #1627
Opened 2021-02-10 12:56 UTC by karenyavine

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
* Adds colors for future support for critical severity
* Adds default fallback color for unknown severities

2021-02-10 12:57 UTC, gitphill commented on src/cli/commands/protect/prompts.ts
> +    : defaultSeverityColor;
`legacySeveritiesColourMapping[severity] || defaultSeverityColor`?

2021-02-11 12:22 UTC, aron approved these changes

2021-02-11 12:22 UTC, aron commented on src/cli/commands/test/iac-output.ts
> +    : defaultSeverityColor;
Instead of exporting both `severitiesColourMapping` and `defaultSeverityColor` and having this logic in each file, how about just exporting a single function (maybe: `severityColor(sev: SEVERITY)`?) that does this for you and returns the `colorFunc()` function? Would clean up all the call sites.

2021-02-15 07:08 UTC, karenyavine commented on src/lib/snyk-test/common.ts
> +  CRITICAL = 'critical',
@JackuB Any reason we have severities enum defined twice? once here and once in `src/lib/snyk-test/legacy.ts`

2021-02-16 12:51 UTC, JackuB requested changes
Should this also be documented in the CLI help?

Left some minor questions before approving

2021-02-16 12:51 UTC, JackuB commented on src/lib/snyk-test/common.ts
> +  CRITICAL = 'critical',
Don't think it's intended

2021-02-16 12:51 UTC, JackuB commented on src/lib/snyk-test/common.ts
> +export function getSeveritiesColour(severity) {
<img width="554" alt="Screen Shot 2021-02-16 at 13 46 39" src="https://user-images.githubusercontent.com/1788727/108064778-701ab500-705d-11eb-8aac-5ff62a58bd4c.png">

Shouldn't this file be typed since we are introducing these functions?

2021-02-16 12:51 UTC, JackuB commented on src/cli/commands/test/iac-output.ts
> +  const severityColor = getSeveritiesColour(issue.severity);
If I'm reading this right, we are planning to introduce the `critical` severity in a `issue.severity` field, this means you went for a breaking change on the API level? Are you worried about older clients in that case?

2021-02-16 12:59 UTC, karenyavine commented on src/cli/commands/test/iac-output.ts
> +  const severityColor = getSeveritiesColour(issue.severity);
Yes it will be a breaking change, but will be sent only to clients using CLI version greater than or equal to whatever version this gets shipped in

2021-02-16 14:45 UTC, JackuB approved these changes

2021-02-17 08:05 UTC, merged