Feat/add snyk code test support
snyk/snyk pull request #1640
Opened 2021-02-16 08:25 UTC by ArturSnyk

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
This introduces an mpv usage for snyk code

#### Where should the reviewer start?
you should have the snykcode cli's ff,
and run it with `snyk code test` or `snyk code test <project_path>`

#### How should this be manually tested?
`snyk code test` or `snyk code test <project_path>`

#### Any background context you want to provide?
we will be adding more functionality around this flow, more error handling, analytics, and output functionality, later on

#### What are the relevant tickets?
https://snyksec.atlassian.net/browse/COD-123

#### Screenshots

![image](https://user-images.githubusercontent.com/42909729/108036729-45226800-7041-11eb-8f7f-4a8e87656df6.png)

#### Additional questions

2021-02-16 09:31 UTC, dkontorovskyy reviewed
![](https://media.giphy.com/media/26njPmXyeB1kCAauk/giphy.gif)

2021-02-17 17:17 UTC, ArturSnyk commented
The test Is failing because of a security issue we have in the library that was added to this PR `code-client`.

It is ok to review this or. we won't merge before this issue is fixed :) and we are working on it

2021-02-17 18:21 UTC, robcresswell requested changes
Just putting a blocker for ecosys arch to review

2021-02-19 12:15 UTC, gitphill commented on config.default.json
> +  "CODE_CLIENT_PROXY_URL": "http://deeproxy.dev.snyk.io"
shouldn't reference dev in this file? (I see API is pointing at production not dev)

2021-02-19 15:15 UTC, JackuB requested changes
There is still a vulnerability in coming from the `fast-glob`. We can't merge it if it's there

<img width="714" alt="Screen Shot 2021-02-19 at 16 07 51" src="https://user-images.githubusercontent.com/1788727/108522772-77e09080-72cd-11eb-9c98-50433a927c23.png">

2021-03-02 09:28 UTC, closed without merging

2021-03-02 09:29 UTC, ArturSnyk commented
closed in favor of https://github.com/snyk/snyk/pull/1664