fix: avoid ascii codes in non-tty and no color output
snyk/snyk pull request #1655
Opened 2021-02-22 17:27 UTC by jahed-snyk

This fixes it for help commands. Chalk already handles other output.

2021-02-22 17:56 UTC, maxjeffos requested changes
The PR description could use some more info, too (like "why"). Is there a reason you didn't use at least part of the PR description template?

2021-02-22 17:56 UTC, maxjeffos commented on src/cli/commands/help.ts
> +const readHelpFile = (filename: string): string => {
Don't think we have a policy on this, but this kind of function definition is not particularly helpful unless it is required (i.e. when using as a closure) and does not appear to be inline with the norm.

2021-02-22 18:31 UTC, jahed-snyk commented
>Is there a reason you didn't use at least part of the PR description template?

I asked and was told it was fine. I agree though; the why is important. I'll polish this up tomorrow. 👍

2021-02-23 09:06 UTC, JackuB commented
Ha, my bad, told @jahed-snyk to not fill it :)

2021-02-24 01:59 UTC, maxjeffos approved these changes

2021-02-24 16:17 UTC, jahed-snyk commented on src/cli/commands/help.ts
> +const readHelpFile = (filename: string): string => {
I've changed it to use plain old functions.

2021-02-24 17:23 UTC, jahed-snyk commented
Updated OP with details now. Also added a question:

>strip-ansi is a part of chalk so it's not added as a direct dependency, but as best practice, maybe it should be?

2021-02-26 16:20 UTC, merged

2021-02-26 16:21 UTC, jahed-snyk commented
Merged. To answer the remaining question, we already have strip-ansi in the package.json. 🙃