feat: add default created date to ignores
snyk/snyk pull request #1670
Opened 2021-03-02 10:55 UTC by gablaxian

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

In all the time we’ve had ignores in the CLI, we’ve never set a created date of the current timestamp to them, which is counter to what we do in the UI/API.

Now is the time to change that.

#### Where should the reviewer start?

Pull this down and build it locally.

#### How should this be manually tested?

- Find a monitored project which has issues
- Find an issue and run ignore, e.g `snyk-dev ignore --id=npm:qs:20140806`
- Call the aggregated issues endpoint for the project to see that the created date is in the returned ignore object on the issue, `http://[host]/api/v1/org/orgId/project/projectId/aggregated-issues`

2021-03-02 18:03 UTC, dtrunley-snyk approved these changes

2021-03-04 10:08 UTC, jahed-snyk requested changes

2021-03-04 10:17 UTC, gablaxian commented on test/system/cli.test.ts
> +    t.type(new Date(pol.ignore.created), Date);
If the string passed in is not parseable as a date, then this would not be a date.

2021-03-04 10:26 UTC, gablaxian commented on src/cli/commands/ignore.ts
> +                created: new Date(),
I think the docs only show what is required for an ignore policy, locally. The rest is specific to Registry, where, we also do not have a robust Type for an ignore. It's old code which needs some love from the team responsible for that area. Which is not _this_ area. It’s... complicated.

2021-03-04 10:28 UTC, gablaxian commented on test/system/cli.test.ts
> +    const createdDateString = new Date(
Oh, interesting! I wasn't aware of sinon fake timers. Will take a look.

2021-03-04 10:29 UTC, gablaxian commented on test/system/cli.test.ts
> +    t.type(new Date(pol.ignore.created), Date);
But, as you mentioned below with fake timers, that would also be a better solution here.

2021-03-04 11:38 UTC, jahed-snyk commented on test/system/cli.test.ts
> +    t.type(new Date(pol.ignore.created), Date);
👍  on fake timers.

Just to clarify, an invalid date created with new Date will still be an `instanceof` Date (but will be flagged as "Invalid"). e.g. this test will pass:

```js
import { test } from 'tap';

test('not a date', (t) => {
  t.plan(1);
  t.type(new Date('not a date'), 'Date');
});
```

The only way to detect an Invalid Date is a `NaN` test with `getTime()`. One of those weird JS things, which is why a date library like date-fns would help us a lot. https://date-fns.org/v2.18.0/docs/isValid

2021-03-04 14:26 UTC, JackuB commented on test/system/cli.test.ts
> +    const createdDateString = new Date(
There are also built-in fake timers in Jest: https://jestjs.io/docs/en/timer-mocks - found them a bit easier to use than Sinon ones

2021-03-04 17:18 UTC, gablaxian commented on test/system/cli.test.ts
> +    const createdDateString = new Date(
Then I'd have to convert all this over to Jest ;)

2021-03-05 10:22 UTC, jahed-snyk approved these changes

2021-03-05 12:11 UTC, merged