Feat/fetch wasm from s3 cc 627
snyk/snyk pull request #1690
Opened 2021-03-06 19:07 UTC by ipapast

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-03-08 07:47 UTC, rontalx commented on jest.config.js
> +    '<rootDir>\\test\\iac-unit-tests\\*.spec.ts', // for Windows
should be able to rebase from master and have these now.

2021-03-08 07:47 UTC, rontalx commented on .github/CODEOWNERS
> +test/iac-unit-tests/ @snyk/cloudconfig
should be able to rebase from master and have these now.

2021-03-08 13:48 UTC, rontalx commented on src/lib/types.ts
> +  cacheDir?: boolean;
nit:
got a comment from Ben to rename this to: `cache-directory`

2021-03-08 13:51 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/fetch-wasm-bundle.ts
> +import * as fs from 'fs';
I thought of bundling all of this code inside the `local-cache.ts` module, so it handles all logic related to the local cache and downloading.
Maybe we can rename it to something like `policy-provider.ts` or so.
WDYT?

2021-03-08 13:55 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/index.ts
> +
Following:
https://github.com/snyk/snyk/pull/1690/files#r589434889
Can we move these lines into the unified module?
so all cache/download logic is encapsulated there.
Then also the test command will keep a cool neat convention, for example something like that:
```
  import { initPolicyProvider } from './local-cache.ts'
  ....
  await initPolicyProvider(options);     //
  const filesToParse = await loadFiles(pathToScan);
  const { parsedFiles, failedFiles } = await parseFiles(filesToParse);
  const scannedFiles = await scanFiles(parsedFiles);
  const formattedResults = formatScanResults(scannedFiles, options);
```

2021-03-08 14:28 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/fetch-wasm-bundle.ts
> +  return extractBundle(bundlePath);
Although this approach with is cool, I'd prefer to avoid this stream & callback implementation.
it's hard to comprehend from first look, and I don't think it adds value due to the synchronous nature of this flow.
I'd suggest checking if you can promisify the `https.get` (I know we use `needle` in the CLI so maybe that can be utilised).
so the flow eventually is as simple as:
```
// await on downloading the file
// synchronously unzipping it with tar
// synchronously write it to the directory.
```
it's easier to read and the readers doesn't need to wrap their heads around asynchronous streams/pipes and callbacks, just to realise it's a simple synchronous flow. 
on other scenarios it can be great, I think its less convenient here.
WDYT?

2021-03-08 14:30 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/fetch-wasm-bundle.ts
> +        'Please check that the current directory has write permissions',
Looking good, I'd double check with Ben for the specific wording.

2021-03-08 14:34 UTC, rontalx commented on test/iac-unit-tests/fetch-wasm-bundle.spec.ts
> +import { streamToFile } from '../../src/cli/commands/test/iac-local-execution/fetch-wasm-bundle';
you mentioned that you're adding tests, 
double checking you're planning to test the public/exposable method of the module `fetchBundle`?

2021-03-08 14:43 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/index.ts
> +  if (!options.cacheDir) {
@benlaplanche @ipapast 
Following our sync today, double checking we're aligned...
For the beta-release:
- the `--cache-directory` can be provided, which will avoid the forced downloading.
- in this release the `--cache-directory` serves merely as a boolean flag to allow avoid the forced download every time. emphasising it is still not supportive of providing a custom directory, this will be added for the GA. 
- open question: how would we expect the `--cache-directory` flag to work if the bundle wasn't downloaded yet, download it? or error out and expect a first iteration without it to run in order to do the initial bundle fetch.
I'd say, `--cache-directory` should download a bundle if there's non present (will happen for the first run with that flag.).

Although an edge-case, I think it can be impactful in terms of experience.
WDYT?

2021-03-08 14:49 UTC, rontalx commented
great work! left some comments.

2021-03-09 09:19 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/fetch-wasm-bundle.ts
> +  return extractBundle(bundlePath);
Thanks, I changed this part to be synchronous as you suggested, I hope it reads better now

2021-03-09 12:35 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/file-utils.ts
> +  const iacPath: fs.PathLike = path.join('.iac-data/');
mind adding small `TODO` notes on the places it uses `'.iac-data/'` that in the future it would be custom?

2021-03-09 12:42 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/index.ts
> +  if (!options.cacheDir) {
reverting this flag as discussed

2021-03-09 14:21 UTC, aron commented on src/cli/commands/test/iac-local-execution/index.ts
> +  if (!options.cacheDir) {
Not for now, but my understanding of this flag, in the GA state based on experience with other tools is as follows.

1) Without the flag Snyk will default to `$(pwd)/.snyk-iac`.
  1) If the .snyk-iac directory exists the CLI will check if the contained policies are present, valid and up-to-date. And if stale either prompt to download or download automatically in the background.
2) With the `--cache-directory` flag the CLI will replace the `$(pwd)/.snyk-iac` path with that provided by the user. The same steps as above apply.

I don't think the flag should have any impact on the download behaviour, it should simply be used to configure a path.

2021-03-09 14:27 UTC, aron commented on src/cli/commands/test/iac-local-execution/index.ts
> +  if (!options.cacheDir) {
> instead of just running with the flag, and have it download the files to the provided directory if it's empty.

This is what I intended to say. I've updated the comment to hopefully clarify.

2021-03-09 14:30 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/index.ts
> +  if (!options.cacheDir) {
so we are talking on the same thing 🤓 
Anyway for now let's extract this flag from this PR for simplicity.
We can add it in the coming sprint.

2021-03-09 14:31 UTC, aron commented on src/cli/commands/test/iac-local-execution/file-utils.ts
> +    fs.createReadStream(bundlePath)
Not for now, but why write the bundle to disk when we can pipe the HTTP stream directly into `tar.x()`?

2021-03-09 18:42 UTC, ipapast commented on .circleci/config.yml
> +            shellspec -f d -e REGRESSION_TEST=1 -e SNYK_IAC_SKIP_BUNDLE_DOWNLOAD=true
This is to provide an env var for IaC smoke tests -we use local fixtures in the tests but now the implementation downloads new policies everytime. We wanted to skip the download for now by adding this var.

2021-03-09 18:56 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/file-utils.ts
> +    fs.createReadStream(bundlePath)
changed this, writing is removed now

2021-03-10 06:34 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/index.ts
> +  await initLocalCache();
yasss ✨

2021-03-10 06:38 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/local-cache.ts
> +      'https://cloud-config-policy-bundles.s3-eu-west-1.amazonaws.com/bundle.tar.gz';
nit:
maybe worth adding a small TODO/comment that it will be replaced with snyk . io domain soon

2021-03-10 06:41 UTC, rontalx approved these changes
great stuff 👏

2021-03-10 09:26 UTC, ipapast commented on jest.config.js
> +    '<rootDir>\\test\\iac-unit-tests\\*.spec.ts', // for Windows
Those were there already. Line 13 has an extra comma in the end of the comment and didn't cause conflicts. I can remove the line.

2021-03-10 09:29 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/local-cache.ts
> +      'https://cloud-config-policy-bundles.s3-eu-west-1.amazonaws.com/bundle.tar.gz';
We haven't taken a decision officially with what it would be replaced exactly so I think I'll skip this

2021-03-10 09:29 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/local-cache.ts
> +  if (!process.env.SNYK_IAC_SKIP_BUNDLE_DOWNLOAD) {
Just personal preference I guess 😅 I thought it would be much easier to clean afterwards

2021-03-10 10:08 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/file-utils.ts
> +  const iacPath: fs.PathLike = path.join('.iac-data/');
done

2021-03-10 10:13 UTC, jahed-snyk requested changes

2021-03-10 10:13 UTC, jahed-snyk commented on jest.config.js
> +    '<rootDir>\\test\\iac-unit-tests\\*.spec.ts', // for Windows
It looks like Line 10 has been moving to Line 13 and Line 14 and 15 are duplicates of Line 11 and 13. Rolling back all changes to `jest.config.js` in this PR should fix this.

2021-03-10 10:13 UTC, jahed-snyk commented on .circleci/config.yml
> +            shellspec -f d -e REGRESSION_TEST=1 -e SNYK_IAC_SKIP_BUNDLE_DOWNLOAD=true
I'm not sure about this change. The goal of smoke tests is to capture production issues so skipping a production step kind of defeats its purpose. Mentioning @JackuB as I don't have full context of smoke tests.

2021-03-10 10:48 UTC, ipapast commented on .circleci/config.yml
> +            shellspec -f d -e REGRESSION_TEST=1 -e SNYK_IAC_SKIP_BUNDLE_DOWNLOAD=true
Hi @jahed-snyk , @JackuB, I just want to clarify that we are not skipping the tests but the download of an artifact. The download step now overwrites the local fixtures we are using in the smoke tests on every download, so the expected results change. 
We introduced this var temporarily, we will think of how to do this better and according to the next steps of this flow, but for now we want the tests to run against the fixed set of fixtures.

Does this make more sense?

2021-03-10 11:16 UTC, jahed-snyk commented on .circleci/config.yml
> +            shellspec -f d -e REGRESSION_TEST=1 -e SNYK_IAC_SKIP_BUNDLE_DOWNLOAD=true
Thanks for clarifying. That makes sense.

Bear with me for a bit as I get some feedback on the rest of the changes from the team (I don't have enough context).

2021-03-10 11:53 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/local-cache.ts
> +      'https://cloud-config-policy-bundles.s3-eu-west-1.amazonaws.com/bundle.tar.gz';
following our conversation and drift of the bundle,
let's make sure to use here an explicit bundle name with a tagged version so we keep track of what is being used., and we know is working.
as we're not covering the download scenario of specific bundles in tests yet.
❗️🚨

2021-03-10 14:16 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/local-cache.ts
> +      'https://cloud-config-policy-bundles.s3-eu-west-1.amazonaws.com/bundle.tar.gz';
ok after what we discussed now, ignore this :)

2021-03-10 14:29 UTC, merged