feat: convert args into paths & options
snyk/snyk pull request #1698
Opened 2021-03-08 20:02 UTC by lili2311

- [ ] Ready for review
- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [ ] Reviewed by Snyk internal team

#### What does this PR do?
Extract command args processing that generate the test paths & options from input which can be a variety of shapes coming in. All in preparation for a new command that will need to re-use most of snyk test flow.

2021-03-09 09:55 UTC, JackuB requested changes

2021-03-09 09:55 UTC, JackuB commented on src/cli/commands/process-command-args.ts
> +import { Options } from '../../lib/types';
This module should have an unit test. Ideally a jest test

@maxjeffos @jahed-snyk we had plans to setup unit testing folder, right?

2021-03-09 11:19 UTC, lili2311 commented on src/cli/commands/process-command-args.ts
> +import { Options } from '../../lib/types';
we seem to only have `tap acceptance` + `tap system` + `tap other` and `jest all in top level directory`

This would be a new test so it would be jest and has somewhere to go, however I agree it would be great if we can start managing the test structure and move away from tap. We want to be able to put the tests in the same directory structure as the code being tested.

2021-03-09 14:48 UTC, lili2311 commented on src/cli/commands/process-command-args.ts
> +import { Options } from '../../lib/types';
Added a test

2021-03-10 13:38 UTC, JackuB approved these changes

2021-03-10 13:41 UTC, merged