refactor: set default test options
snyk/snyk pull request #1704
Opened 2021-03-10 11:58 UTC by lili2311

- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
refactor settings default test options so it can be re-used in another command that relies on test running first

2021-03-11 12:46 UTC, aviadhahami approved these changes
lgtm :)

2021-03-11 14:43 UTC, JackuB requested changes

2021-03-11 14:43 UTC, JackuB commented on src/cli/commands/test/set-default-test-options.ts
> +export function setDefaultTestOptions(
I believe we should keep adding jest-unit test for these new modules

2021-03-11 16:54 UTC, lili2311 commented on src/cli/commands/test/set-default-test-options.ts
> +export function setDefaultTestOptions(
how are these structured? Right now I am dumping all new tests into top level test directory because of the jest pattern restrictions 😢 can we update this to allow us to add tests in correct folder structures instead?
- code: `src/lib/index.ts`
- test: `test/lib/index.spec.ts`? Maybe for now `test/jest/unit/lib/index.spec.ts` until we fully migrate to Jest?

It will be hard to separate jest tests later from system/acceptance/unit etc

2021-03-11 18:05 UTC, lili2311 commented on src/cli/commands/test/set-default-test-options.ts
> +    .toString()
this essentially adds support for `--show-vulnerable-paths` to be treated as `--show-vulnerable-paths=true` WDYT?

Otherwise if you run test with `snyk test --show-vulnerable-paths` you get a bad error that says
`toLowerCase is not a function` because it is not a string. Or alternative is to add validation for this options and throw outside of this function somewhere probably

2021-03-12 09:47 UTC, lili2311 commented on src/lib/types.ts
> -  interactive: boolean;
this is a protect option for wizard only

2021-03-12 09:47 UTC, lili2311 commented on src/cli/commands/test/set-default-test-options.ts
> +export function setDefaultTestOptions(
Test added, please advise if it can move somewhere better than top level of test directory

2021-03-12 10:42 UTC, lili2311 commented on src/cli/commands/test/set-default-test-options.ts
> +    .toString()
@gitphill while @aviadhahami is off, could you help 👀 ?

2021-03-12 10:46 UTC, JackuB approved these changes

2021-03-12 10:46 UTC, JackuB commented on src/cli/commands/test/set-default-test-options.ts
> +    .toString()
:+1: this sounds in line with how arg parsing libraries should treat this

2021-03-12 10:46 UTC, JackuB commented on test/set-default-test-options.spec.ts
> +      org: undefined,
Just curious, in the jest's equals logic, is `org: undefined` same as not having `org` key at all?

2021-03-12 10:58 UTC, lili2311 commented on test/set-default-test-options.spec.ts
> +      org: undefined,
it does indeed!

2021-03-12 11:55 UTC, miiila approved these changes

2021-03-12 12:51 UTC, JackuB commented
Just a nit, noticed a typo in the commit message, which would propagate it to the release notes:

```diff
features:
- delete vuln paths option once transofrmed + tests
+ delete vuln paths option once transformed
```

2021-03-12 15:07 UTC, merged