fix: jest config not provided
snyk/snyk pull request #1731
Opened 2021-03-16 13:21 UTC by rontalx

#### What does this PR do?
TLDR: jest was running with an explicit path instead of the jest config, causing some unit-tests to be skipped in the CI.
See thread for details:
https://snyk.slack.com/archives/C0127HWU0E7/p1615899204013500

2021-03-16 18:21 UTC, rontalx commented on jest.config.js
> -    '<rootDir>/packages/**/test/**/*.spec.ts',
this wasn't running before at all, removing it so the test-suite remains aligned like it was before.

2021-03-16 21:46 UTC, maxjeffos requested changes
@rontalx I made a couple suggestions to fix the new unit tests to run

2021-03-16 21:46 UTC, maxjeffos commented on .circleci/config.yml
> +                command: npm run test:jest-unit-tests
```suggestion
                command: npm run test:jest-unit
```

2021-03-16 21:46 UTC, maxjeffos commented on .circleci/config.yml
> +                command: npm run test:jest-unit-tests
```suggestion
                command: npm run test:jest-unit
```

2021-03-17 13:38 UTC, maxjeffos approved these changes

2021-03-17 15:20 UTC, aron commented on test/cli-json-file-output.spec.ts
> +    test.skip(
What's the plan to unskip this one?

2021-03-17 15:22 UTC, aron approved these changes
Approved but would like someone else to review the `skip` call in test/cli-json-file-output.spec.ts

2021-03-17 15:22 UTC, rontalx commented on test/cli-json-file-output.spec.ts
> +    test.skip(
hammer proposed to skip it for now, Tardis are working on fixing this flakey test:
https://snyk.slack.com/archives/C01D6U0KHGC/p1615982085024100
https://snyk.slack.com/archives/CFTAUCYQ7/p1615970075003300

2021-03-17 15:24 UTC, rontalx commented on test/cli-json-file-output.spec.ts
> +    test.skip(
@anthogez FYI, skipped it here based on @maxjeffos recommendation from the threads.

2021-03-17 15:26 UTC, merged

2021-03-17 15:31 UTC, anthogez commented on test/cli-json-file-output.spec.ts
> +    test.skip(
@rontalx To clarify Tardis proposed to skip the test `test/cli-json-file-output.spec.ts` that belongs to Hammer.
Tardis work is done here because `test/ecosystems-monitor-cpp.spec.ts` is not the root cause of the issue but this file that is currently flaking for windows and is under Hammer ownership.

By decoupling the `/` character in unlinkSync(`./${jsonOutputFilename}`); and giving it a generic handling that works for both Unix and Windows OS - should solve the flakiness for the 1st failed test
https://github.com/snyk/snyk/blob/master/test/cli-json-file-output.spec.ts#L84

cc @aron

2021-03-17 16:08 UTC, rontalx commented on test/cli-json-file-output.spec.ts
> +    test.skip(
right, sry, it's a hammer tests, and @maxjeffos and I are aligned on it 👍