Feat/iac org settings
snyk/snyk pull request #1825
Opened 2021-04-16 08:11 UTC by ipapast

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-04-16 14:26 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +  const filteredResults: IacFileScanResult[] = [...scannedFiles];
I created a copy of the original array to be more "functional" (input/output)

2021-04-16 15:10 UTC, aron requested changes
Looks great 🙌  some small changes requested inline to clean up the error handling and type casting. Also the loops in `getCustomPoliciesAndUpdate()` need a second look, as they're currently mutating the input and iterating over the files twice. 

Lastly, is the test file intended to be empty or was this pushed too early?

2021-04-16 15:10 UTC, aron commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +      resolve(res.body);
Feels like we should handle the `res.statusCode` here and only resolve if we have a 2xx response and reject otherwise? That will clean up the error handling in the caller where we check for the error in the body which shouldn't have an error property.

2021-04-16 15:10 UTC, aron commented on src/cli/commands/test/iac-local-execution/index.ts
> +  const formattedResults = await formatScanResults(scannedFiles, options);
What made you decide to do the transformation inside formatScanResults vs. doing the transform here on a new line, then passing the transformed results into `formatScannedResults()`? This would mean that the format function remains only responsible for formatting the files and not applying overrides.

2021-04-16 15:10 UTC, aron commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +      return violatedPolicy.severity !== ('none' as SEVERITY);
To fix this cast I suggest we update the `PolicyMetadata` interface to define `severity` as `SEVERITY | "none"` and add a comment that the "None" value can be provided by the backend.

2021-04-16 15:10 UTC, aron commented on src/cli/commands/test/iac-local-execution/types.ts
> +  ignoreSettings: object;
Can we fill this out completely based on our knowledge of the object from Registry.

2021-04-16 15:15 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/types.ts
> +  ignoreSettings: object;
Sorry, I'm confused with this question(?). What do you mean? Registry would give us these fields only?

2021-04-16 15:20 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +  const updatedScannedFiles: IacFileScanResult[] = [...scannedFiles];
🤦

2021-04-16 15:40 UTC, aron commented on src/cli/commands/test/iac-local-execution/types.ts
> +  ignoreSettings: object;
Sorry, the fields are defined here: https://github.com/snyk/registry/blob/c7a710b13447f1eb2909218a9983de50bb6c22f6/src/lib/types/index.ts#L134-L138

2021-04-16 15:57 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +    this.userMessage = ''; // Not a user facing error.
Hm, yes debating it if we want to fail if registry fails. I'll double check with Ben 👍

2021-04-16 17:40 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +  });
🤕  thank you!

2021-04-19 07:55 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/apply-custom-severities.ts
> +  return scannedFiles.map((file) => {
let's add a check to `customPolicies` object key count before that, so if it's empty we do not re-iterate on all the scanned files and clone them.

2021-04-19 07:55 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/index.ts
> +  const formattedResults = await formatScanResults(scannedFiles, options);
Yeah, I put it back to the index.ts now, I have split the modules according to what they do :)

2021-04-19 07:58 UTC, ipapast commented
Note: Some tests will be most probably converted to parameterized ones this morning, there is room to remove duplication.

2021-04-19 09:10 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +import { IaCErrorCodes, IacOrgSettings } from './types';
minor nit:
shall we move `get-iac-org-settings.ts` and `apply-custom-severities.ts`
into a new folder? e.g. `org-settings`?

2021-04-19 09:10 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +      return violatedPolicy.severity !== ('none' as SEVERITY);
It's tricky, I can do that, but then there is another place it would break:
 https://github.com/snyk/snyk/blob/6aea05fe5b3df2adb029dfe02ffade1c249b767c/src/cli/commands/test/iac-local-execution/results-formatter.ts#L117-L125
On the `severitiesToInclude.includes(policy.severity)` we would get the warning:
 `TS2345: Argument of type 'SEVERITY | "none"' is not assignable to parameter of type 'SEVERITY'.   Type '"none"' is not assignable to type 'SEVERITY'.` so we would still need to cast it there.
 _Trying to see if there is a better way..._

2021-04-19 09:14 UTC, rontalx commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +      'We failed to fetch IaC organization settings, including custom severity overrides. Please run the command again with the `-d` flag and contact support@snyk.io with the contents of the output.'
nit:
```suggestion
      'We failed to fetch your organization settings, including custom severity overrides for infrastructure-as-code policies. Please run the command again with the `-d` flag and contact support@snyk.io with the contents of the output.';
```

2021-04-19 09:25 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/types.ts
> +  FailedToGetIacOrgSettingsError = 1080,
@aron 2 questions on this:
- do you think this is the best place to add this? Not sure if it actually needs a new "group" on its own

2021-04-19 10:00 UTC, aron approved these changes
👏 Very nice work. Left a couple of responses to your questions and a suggestion on how to better refine the typing, nothing blocking.

2021-04-19 11:43 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/results-formatter.ts
> +      return violatedPolicy.severity !== ('none' as SEVERITY);
TIL!

2021-04-19 11:54 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/types.ts
> +  customPolicies: Record<string, object>;
Does the severity need to be optional? I think it's fine if it's mandatory, the backend would always return customPolicies with a severity key, if there are any. I'm asking on the optional because that would cause other TS 'undefined' type errors 🤦

2021-04-19 11:56 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +import { IaCErrorCodes, IacOrgSettings } from './types';
Can do

2021-04-19 12:04 UTC, aron commented on src/cli/commands/test/iac-local-execution/types.ts
> +  customPolicies: Record<string, object>;
Yes, fine for now, I was thinking a little ahead where this `customPolicies` is really `Partial<Policy>` where the user could theoretically override any number of fields. In this case severity might not be present.

> I'm asking on the optional because that would cause other TS 'undefined' type errors

Yes, this would require a presence check before using the value.

2021-04-19 12:21 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/types.ts
> +  customPolicies: Record<string, object>;
Right, I left it to optional then, I wasn't thinking that far ahead. 👍

2021-04-19 12:26 UTC, ipapast commented on src/cli/commands/test/iac-local-execution/get-iac-org-settings.ts
> +import { IaCErrorCodes, IacOrgSettings } from './types';
Done done 🥳

2021-04-19 13:15 UTC, merged