feat: ignore unrecognised IaC types [CC-947]
snyk/snyk pull request #2061
Opened 2021-06-25 11:21 UTC by craigfurman

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

ignore unrecognised IaC types

No longer return an error when scanning YAML or JSON files that do not
contain recognised infrastructure as code schemas, e.g. Kubernetes or
CloudFormation. Instead, ignore these files.

In YAML files that contain multiple documents, ignore documents that
contain unrecognised schemas. This includes empty documents.

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

https://snyksec.atlassian.net/browse/CC-947

#### Screenshots

#### Additional questions

2021-06-25 11:50 UTC, craigfurman commented
Regarding the bot message above about smoke tests: a failing regression-smoke test is what led me to change the smoke tests in the first place. I don't really want to change my base branch, as that is a pain for PRs. Would it be ok to push a `smoke/` branch at an identical revision to this branch once I get the tests passing here, and link the action in a comment?

I can't find any guidance in https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md, but https://github.com/snyk/snyk/blob/feat/iac-skip-unrecognised/test/smoke/README.md sort-of-hints this might be ok practice?

2021-06-25 16:43 UTC, craigfurman commented
I pushed a smoke branch (https://github.com/snyk/snyk/runs/2916014071), and that seems to have added a bunch of checks here, presumably because github checks are commit-scoped and not branch-scoped.

2021-06-27 12:06 UTC, aron requested changes
👏 Thanks for picking up this Tier 4 issue so quickly. Implementation looks good and thank you for extending the test suite. I've requested changes to get your thoughts on the question around surfacing the "skipped" files to the upper layers of the system.

2021-06-27 12:06 UTC, aron commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +  }
Under what conditions can we get a non-document here? Is this for the invalid YAML sub-document? I think it would be worth adding a comment or handling this in the layer above.

```
if (parsedFile && checkRequiredFieldsMatch(parsedFile, REQUIRED_K8S_FIELDS)) {
```

2021-06-27 12:06 UTC, aron commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +        return null;
I'm wondering if this is the correct layer to swallow this error. We currently have `IacFileParsed` and `IacFileParseFailure`, I'm wondering if here we should be returning an `IacFileParseFailure` or introducing a third type e.g. `IacFileParseSkipped`.

Then we would filter these out at the result rendering layer by default. This would also allow us to present the total number of skipped files to the user as part of the output and in future we could potentially introduce a `--strict` flag that shows the errors, as I think there is some value in the error messages provided here if you're unclear on why your file was skipped.

Thoughts?

2021-06-29 07:46 UTC, craigfurman commented
Note: this PR preserves the behaviour of printing an error and exiting non-zero when we encounter an unparseable/invalid JSON/yaml. I'm not sure if we want to change that as part of this PR.

2021-07-01 10:23 UTC, craigfurman commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +  }
Invalid YAML sub-docs, or invalid jsons, actually do still throw exceptions. This PR doesn't change that behaviour at all. Do we want to change this, and if so, now or later?

The branch you've highlighted covers the empty YAML sub-document case, which IIRC was one of the motivating cases for the ticket. Empty doc support is test-guarded in this fixture: https://github.com/snyk/snyk/pull/2061/files#diff-d87dcf90807ed0045cbb1e752f4ffbe6b4216d177be5abab4ebe57792b54f5c8R57, and the test that uses it.

2021-07-01 10:47 UTC, craigfurman commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +        return null;
I think we have a bunch of options here. I'll try to lay out my mental model of it:

1. Provide no way for the user to see what's skipped
   * This is what the PR does at the time of writing, and is what is motivating your comment. I can see why this might give us pause, in case users are confused.
1. Print a list of all files skipped
   * Optionally behind a flag, e.g. `--show-skipped`?
   * You mention possibly introducing a `--strict` that treats unrecognised yaml/json as errors, but personally I don't agree with this... it's semantically never an error to skip an unsupported schema. IMO a possible problem with this PR currently is that it's hard for users to figure out _why_ a file they did expect to be scanned is skipped, in case we have a bug in our detection logic.
   * We currently print failure summaries in bold red. Should this list be above or below the failure summary? Maybe non-bold blue?
   * I worry this could be very noisy. An IaC-oriented repository might contain 1000s of json and yaml files.
   * Arguably non json/yaml/tf files are also "skipped" by IaC, and no-one is suggesting erroring/listing these!
1. Print a count of skipped files
   * Possibly behind a feature flag
   * Less noisy than printing them all, but there is information loss here. It doesn't really help the user debug what is going on.

2021-07-01 11:33 UTC, craigfurman commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +        return null;
@aron and I had a zoom about this, summary:

- skipped file diagnostics are probably more noise than signal, so we won't implement them here
- we should ensure we return an error to the user when no recognised types are found, as this is probably a mistake
   - when we find no valid extensions, we already return an error for this reason
   - implicitly, we had an error when no recognised IaC type was found because we errored on every unrecognised yaml/json 😅.

2021-07-01 13:34 UTC, craigfurman commented
Thanks for the review and the conversation @aron 👍 

I've implemented what we agreed, would you mind taking another look?

2021-07-01 13:38 UTC, craigfurman commented on src/cli/commands/test/iac-local-execution/file-parser.ts
> +    throw new NoFilesToScanError();
wdyt about reusing this same error?

2021-07-01 20:47 UTC, aron approved these changes
Nice work, I tried this locally with a bunch of different combinations and it all felt like it was behaving as I would expect.

2021-07-01 20:47 UTC, aron commented on src/cli/commands/test/iac-local-execution/parsers/k8s-or-cloudformation-parser.ts
> +  }
That makes sense 👍

2021-07-01 20:47 UTC, aron commented on src/cli/commands/test/iac-local-execution/file-parser.ts
> +    throw new NoFilesToScanError();
I think it makes perfect sense to re-use the error. One thing to note is that this will mask any `failedFiles` so I wonder if this logic should be `if (parsedFiles.length === 0 && failedFiles.length !== 0) {` 

(also note the `===`, I'd have thought this would be picked up by the linter but generally strict equality `===` is preferred as a stylistic preference in JS vs. `==` which will perform coercion).

2021-07-06 10:36 UTC, craigfurman commented on src/cli/commands/test/iac-local-execution/file-parser.ts
> +    throw new NoFilesToScanError();
Do you actually mean `if (parsedFiles.length === 0 && failedFiles.length === 0)`? i.e, do propagate any exceptions from invalid files instead of masking them.

The way the code is currently written `if (parsedFiles.length == 0)`, when scanning a directory containing one invalid file and one random yaml (e.g. circleci.yaml), we'll get NoFilesToScanError.

If we use `if (parsedFiles.length === 0 && failedFiles.length === 0)`, we'll get "Testing invalid.json... Failed to parse JSON file".

I don't have a strong opinion on which error is more instructive in this case. My gut says NoFilesToScanError, since the user is clearly expecting some snyk iac functionality to be contextually relevant, but it isn't.

re: threequal vs `==`, d'oh 🤦. I keep forgetting this basic javascript mistake.

2021-07-06 10:45 UTC, aron commented on src/cli/commands/test/iac-local-execution/file-parser.ts
> +    throw new NoFilesToScanError();
Sorry you're right, my brain farted. Thanks for explaining your thinking, I'm sold, let's go with your logic and the triple equals.

2021-07-06 12:01 UTC, merged