feat: add snyk code help pages
snyk/snyk pull request #2226
Opened 2021-09-05 16:04 UTC by ArturSnyk

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?
We would like to add help pages for `snyk code` command

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2021-09-06 05:43 UTC, neonnoon approved these changes
> static code analysis scanning

Do we use this term elsewhere? To me it sounds like it should be either analysis or scanning, but not both?

2021-09-16 11:43 UTC, JackuB requested changes

2021-09-16 11:43 UTC, JackuB commented on help/commands-docs/code.md
> +[For more information see the CLI for Snyk Code help page](https://docs.snyk.io/snyk-code/cli-for-snyk-code)
This links to a 404

2021-09-16 11:43 UTC, JackuB commented on help/commands-man/snyk-sast.1
> +.\" generated with Ronn-NG/v0.9.1
Where is this file coming from? It should be `snyk-code.1` like above? A leftover file?

2021-09-16 11:52 UTC, neonnoon commented on help/commands-docs/code.md
> +[For more information see the CLI for Snyk Code help page](https://docs.snyk.io/snyk-code/cli-for-snyk-code)
We'll publish that page as soon as I merge this PR. Deadlock? 😄

2021-09-16 11:55 UTC, neonnoon commented on help/commands-man/snyk-sast.1
> +.\" generated with Ronn-NG/v0.9.1
You are right, nice catch!

2021-09-16 12:21 UTC, JackuB approved these changes

2021-09-16 13:12 UTC, merged