WIP feat: add snyk apps create and delete command
snyk/snyk pull request #2396
Opened 2021-11-29 12:38 UTC by love-bhardwaj

- [ x ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

Adds `$snyk apps` command to the Snyk CLI
- `create` command to create a Snyk App
- `delete` command to delete a Snyk App
- `config` value `V3endpoint` to configure the Snyk V3 API endpoint base URL
- Initial acceptance to test the `create` command

#### Where should the reviewer start?

- `src/cli/commands/apps`

#### How should this be manually tested?

Both these commands use prompts for user inputs. To manually test `$snyk apps create` and `$snyk apps delete`

#### Any background context you want to provide?

We at `#team-moose` are starting our investigation to see how to provide users with a CLI to manage Snyk Apps. We have had a discussion with `#team-hammer` in the past and this is our first effort at doing so.

2021-11-29 15:46 UTC, mitechie commented
I think that any and all apps commands should require a --beta argument to function for now to acknowledge that this UX/experience can change. I'm not sure on "create" vs "submit" or "add" or some other function. I'd like to map out the workflow of using the CLI from both an app developer and app consumer perspective and make sure the language the CLI makes sense and distinguishes between the two user stories and their workflows nicely before doing anything that isn't --beta or noted as unfinished/etc.

2021-11-29 17:13 UTC, love-bhardwaj commented
> I think that any and all apps commands should require a --beta argument to function for now to acknowledge that this UX/experience can change. I'm not sure on "create" vs "submit" or "add" or some other function. I'd like to map out the workflow of using the CLI from both an app developer and app consumer perspective and make sure the language the CLI makes sense and distinguishes between the two user stories and their workflows nicely before doing anything that isn't --beta or noted as unfinished/etc.

I believe this will be behind a feature flag before we release it. So the `--beta` flag won't be required. As for the verbs used for the CLI commands. The idea is to build an interactive CLI with user prompts. Tomorrow if we add features for both consumers and developers that we could further prompt users to select options and work accordingly. 

For example, a user wants to list apps. We can ask follow-up questions like List apps created by your org? or list apps you have installed on your org.

2022-01-07 14:36 UTC, jgresty commented
Should moose be codeowners of the apps commands?

2022-01-07 14:38 UTC, JackuB reviewed
Left some comments and suggestions 👍

2022-01-07 14:38 UTC, JackuB commented on src/lib/apps/inputValidator.ts
> +    '^(http(s)?:\\/\\/)?' + // protocol
What is the intent for this URL validator? What kind of URLs are considered valid? It mentions URI in the function comment as well - should be following the [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986)?

Because here it's marking protocol as optional with `?`, thus allowing strings like `test.com`.

Node.js `URL` might be helpful here https://nodejs.org/docs/latest-v10.x/api/url.html if we just want to validate a general shape of the string.

2022-01-07 14:38 UTC, JackuB commented on src/lib/apps/inputValidator.ts
> +  return uuid.validate(input) ? true : 'Invalid UUID provided';
Do we care about the version of UUID we are validating, or any will do? https://www.npmjs.com/package/uuid#uuidvalidatestr

2022-01-07 14:38 UTC, JackuB commented on src/cli/commands/apps/index.ts
> +    debug(`Not a valid sub command ${commandVerb1}`);
I'd consider updating the error message a bit:

```suggestion
    debug(`Unknown subcommand: ${commandVerb1}`);
```

2022-01-07 14:38 UTC, JackuB commented on src/cli/commands/apps/index.ts
> +      if (res) return res;
Wouldn't it be better if `createApp` always returned something? When is it a valid case that it will return `undefined`? The `handleV3Error` always throw, and would trigger a `catch`? Then you could lose this `if`, as it serves no purpose right now.

2022-01-07 14:59 UTC, love-bhardwaj commented on src/lib/apps/constants.ts
> +    'The available sub-commands are:',
Thanks and agreed we should replicate the rest of the commands to maintain consistency.

2022-01-07 19:30 UTC, DarrellMozingo commented on src/cli/commands/apps/create-app.ts
> +    const response = await makeRequestV3<ICreateAppRes, IV3ErrorResponse>(
V3 as a nae is being communicated widely & to customers, afaik. It's also a major version in the url path, eg `api.snyk.io/v3`, so quite front & centre. There might be a v4 one day (hopefully not 😅 ). Also helps in support in the future imo, like Googling. Knowing a post/article is for Snyk API V3 is more clear if there ever is a v4, instead of just "Snyk API" and not being sure.

2022-01-07 20:21 UTC, DarrellMozingo reviewed
Muy bueno, nice work Love! 👏   Left lots of questions & nits below!

2022-01-07 20:21 UTC, DarrellMozingo commented on test/jest/util/runCommand.ts
> +      childProcess.stdin.write(inputs[0]);
Worth a console/logger writ of what `inputs[0]` is being sent in the loop?

2022-01-07 20:21 UTC, DarrellMozingo commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        'apps create --interactive --experimental',
Should this be `-i`?

2022-01-07 20:21 UTC, DarrellMozingo commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +    server = fakeServer(baseApi, env.SNYK_TOKEN);
This is just stubbing responses, no? Do we ever assert the data we're sending to the api to ensure we're parsing values correctly?

2022-01-07 20:21 UTC, DarrellMozingo commented on src/lib/apps/inputValidator.ts
> +export function validateAllURL(input: string): string | boolean {
Could all these validation methods be unit tested? Heavily for the regex ones below if we can't leverage oss alternatives that are tested.

2022-01-07 20:21 UTC, DarrellMozingo commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        [testData.appName, ENTER, 'something-invalid', ENTER],
This is a neat testing strategy! I'm curious to see how flakey it might become...

2022-01-07 20:21 UTC, DarrellMozingo commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        "Your Snyk App's redirect URIs (comma seprated list.",
Single quotes? Not sure if there's a reason for double, or if linting is setup for the CLI...

2022-01-07 20:45 UTC, love-bhardwaj commented on src/lib/apps/utils.ts
> +export function createDisplayErrTable(
Maybe I should have asked this question earlier. `consistency` was the reason I was using `table` for `apps` related command since I could find helpers functions to display messages.

2022-01-07 20:55 UTC, love-bhardwaj commented on src/cli/commands/apps/create-app.ts
> +    const response = await makeRequestV3<ICreateAppRes, IV3ErrorResponse>(
Adding to Darrell's comment. We could have used `API` but the thing is it is already being used in other places like `snyk config set api=<token>` and most of the code still relies on `v1`. So I wanted to make sure we don't confuse it and have a distinctive understanding of both.

2022-01-07 20:58 UTC, love-bhardwaj commented on src/lib/apps/inputValidator.ts
> +    '^(http(s)?:\\/\\/)?' + // protocol
This is a pretty custom regex that supports `localhost` and other URL that we could think of. That the user may use. I believe, for the API `localhost:3000` works as well. We are open to suggestions if there is a better way to do so 🙂 .

2022-01-07 20:59 UTC, love-bhardwaj commented on src/lib/apps/inputValidator.ts
> +  return uuid.validate(input) ? true : 'Invalid UUID provided';
Good questions, I don't have a definitive answer but whatever versions the `orgId` are off, which I am not sure.

2022-01-07 21:08 UTC, love-bhardwaj commented on src/lib/request/promise.ts
> +    request.makeRequest(payload, (error, res, body) => {
Correct, request module has the debugger to `debug(payload)` 🙂

2022-01-07 21:10 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +      const snykAppRedirectUris = answers[SNYK_APP_REDIRECT_URIS].trim().split(
Haven't tested that and don't think we have taken that into consideration. Although we do explicitly tell it is a comma-separated list. But this is a good point, so I will add this to our `todo` list.

2022-01-07 21:17 UTC, love-bhardwaj commented on src/lib/apps/constants.ts
> +const tableData = {
Completely agree as it will also add `consistency`. Would it be alright to create a markdown for all `apps` commands such as `apps create`, `apps list` and so on and use those? Haven't seen this for other commands so would like to confirm before proceeding.

2022-01-07 21:20 UTC, love-bhardwaj commented on src/cli/commands/apps/create-app.ts
> +    spinner.clearAll();
Sorry if I misunderstood, but the problem there was that you would see it spinning even after the text was printing to the terminal and disappear causing a glitchy effect 😓 .

2022-01-07 21:21 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +      // Proceed with interactive
Great idea. I was looking for something similar but haven't been able to focus on it. Added to my `todo` list.

2022-01-07 21:23 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +function validateProcessCreateAppOpts(
Yes, that is part of the plan 😅 but have been delaying it to work on the feedback provided. Another one for the `todo` list 😄

2022-01-07 21:29 UTC, love-bhardwaj commented on src/cli/commands/apps/create-app.ts
> +    headers: getV3Headers(),
`json: true` can surely go in there but not sure about `headers` as it has the authorization header. Will look into this and see if it can be moved 🙂

2022-01-07 21:30 UTC, love-bhardwaj commented on src/lib/request/promise.ts
> +export async function makeRequestV3<T, E>(payload: any): Promise<T> {
A good idea will try that. This was me trying to play with generics to type cast error response.

2022-01-07 21:31 UTC, love-bhardwaj commented on src/lib/apps/v3utils.ts
> +        'Unauthorized: the request requires an authentication token or a token with more permissions.',
I think it does. Sorry, this was implemented a while back at least in terms of coding, but not sure. I will check and confirm. But as far as I remember it does.

2022-01-07 21:42 UTC, DarrellMozingo commented on src/cli/commands/apps/create-app.ts
> +    spinner.clearAll();
Ah you're right, sorry! I read too fast, missed there was text in that handle method afterwards :)

2022-01-10 09:52 UTC, love-bhardwaj commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        "Your Snyk App's redirect URIs (comma seprated list.",
The reason for double quotes is that the content inside the string has a single quote (apostrophe i.e App's) 🙂

2022-01-10 14:41 UTC, DarrellMozingo commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        "Your Snyk App's redirect URIs (comma seprated list.",
Totally missed that, sorry 😄

2022-01-10 15:46 UTC, love-bhardwaj commented on src/lib/apps/inputValidator.ts
> +  return uuid.validate(input) ? true : 'Invalid UUID provided';
`v3` API validates the `UUID` without taking into account the version. So for consistency, we too don't take the version of UUID into account.

2022-01-10 18:48 UTC, love-bhardwaj commented on test/jest/util/runCommand.ts
> +      childProcess.stdin.write(inputs[0]);
My only worry it will lead to a lot of unnecessary data being printed to logs/console.

2022-01-10 18:57 UTC, love-bhardwaj commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +    server = fakeServer(baseApi, env.SNYK_TOKEN);
The stub response has data that is directly returned in the response from the request body. So in other words, we are asserting on the response that the data we sent was sent in the correct format.

2022-01-10 18:58 UTC, love-bhardwaj commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +        [testData.appName, ENTER, 'something-invalid', ENTER],
This was the only reasonable strategy I could find for testing the `--interactive` commands 😅 I took am curious to see the flakiness of it. Initial doubt was that it may not work on Windows, but has been working fine till now 😄

2022-01-10 19:20 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +      const snykAppRedirectUris = answers[SNYK_APP_REDIRECT_URIS].trim().split(
This has been added 🙂

2022-01-10 19:20 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +function validateProcessCreateAppOpts(
✅

2022-01-12 21:50 UTC, jahed-snyk reviewed
I've left some thoughts on a few things but nothing major other than the package-lock.json (which as you mentioned will likely not need to be modified once this is ready).

2022-01-12 21:50 UTC, jahed-snyk commented on src/lib/request/promise.ts
> +    request.makeRequest(payload, (error, res, body) => {
IIRC, if you don't provide a callback, `makeRequest` will return a promise instead so you won't need the promise wrapper.

2022-01-12 21:50 UTC, jahed-snyk commented on src/lib/config.ts
> +config.API_V3 = userConfig.get('v3endpoint') || 'https://api.snyk.io/v3';
You can set `API_V3`'s default in `config.default.json`. That's also where `API`'s default is set and picked up by snyk-config. `process.env.SNYK_API_V3` is also picked up automatically via snyk-config, however, there are some precedence issues when combined with userConfig (config misalignment in general is a known issue).

If you rename `v3endpoint` to `api-v3`, then `process.env.SNYK_CONF_API_V3` will be picked up automatically by userConfig so you don't need to separately define an override later on.

So precedence will be like:

SNYK_CONF_API_V3 > api-v3 in user-config > SNYK_API_V3 > API_V3 in snyk-config

I don't think we need to tie ourselves too much to "endpoint" as it's too ambiguous and inconsistent.

2022-01-12 21:50 UTC, jahed-snyk commented on src/lib/apps/input-validator.ts
> +  for (const i of trimmedInput.split(',')) {
Might be useful to trim each URL after the split as people may put spaces after each comma. Just a common pet peeve of mine...

2022-01-13 08:25 UTC, JackuB commented on src/lib/apps/constants.ts
> +const tableData = {
I'd start with having a single `apps` help page and we can go from there if the doc gets too large. Definitely use markdown rather than loose text strings in the code for such docs

2022-01-13 08:25 UTC, JackuB commented on src/lib/apps/utils.ts
> +export function createDisplayErrTable(
I'd recommend getting rid of the `table` altogether and keep using Markdown for help text and plain strings for errors like the rest of the commands.

2022-01-13 08:27 UTC, JackuB commented on help/cli-commands/apps.md
> +Prints a help text. You may specify a `<COMMAND>` to get more details.
We've recently cleaned up this repeated section of Help files, making them considerably shorter - see for example changes to `snyk auth` command: https://github.com/snyk/snyk/pull/2512/files

You can drop these repeated flags.

2022-01-13 08:28 UTC, JackuB commented on help/cli-commands/apps.md
> +**3**: failure, no supported projects detected<br />
Same for this, as it's not relevant for `apps` command

2022-01-13 08:29 UTC, JackuB commented on src/cli/commands/apps/index.ts
> +): Promise<string | undefined | any> {
`any` here looks like a code smell, especially for a new command/function that this PR is adding

2022-01-13 08:32 UTC, JackuB commented on src/lib/apps/create-app/index.ts
> +        .split(','),
Not sure if it's an issue in this case, but `,` commas are actually allowed characters in the URL, although uncommon. I'd consider adding an edge case to at least check we error out as expected on this.

2022-01-13 08:35 UTC, JackuB commented on src/lib/apps/input-validator.ts
> +  for (const i of trimmedInput.split(',')) {
I'd add to this, that we are doing this trim&split(&trim) check on a few places, it might be useful to use this single function and always return `string[]`?

2022-01-18 14:29 UTC, JackuB commented
Don't mind me, just screwed up a git command when working on #2591. Reverted to the original commit :p

2022-01-26 19:26 UTC, love-bhardwaj commented on src/lib/apps/create-app/index.ts
> +  const snykAppName = answers[SNYK_APP_NAME].trim() as string;
Yes for sure. That will be really great. We lack types for our forked inquirer.

2022-01-26 20:33 UTC, love-bhardwaj commented on test/jest/util/runCommand.ts
> +    setTimeout(() => {
Agreed and thanks for your input on this. Timeouts can be removed, but this is the best I could find to test the interactive mode. If there are better ways to test user prompts like interactive modes, please provide an example I would be happy to incorporate that 🙂 

It would be great! if there is a testing API in the codebase to test such interactive commands. It will help massively going forward as we plan to implement both interactive and scriptable modes.

2022-01-26 20:43 UTC, love-bhardwaj commented on src/lib/request/promise.ts
> +    request.makeRequest(payload, (error, res, body) => {
We are using the `callback` to actually make the response be parsed as an object using `JSON.parse` for all v3 requests 🙂 . So this format actually helps.

2022-01-26 20:58 UTC, love-bhardwaj commented on src/lib/config.ts
> +config.API_V3 = userConfig.get('v3endpoint') || 'https://api.snyk.io/v3';
I tried doing what was suggested but there seem to be some type issues. I may not have understood the working of it completely but I am making changes based on your suggestions 🙂

2022-01-26 21:04 UTC, love-bhardwaj commented on src/lib/apps/input-validator.ts
> +  for (const i of trimmedInput.split(',')) {
For input validation using the `new URL` spaces doesn't seem to affect the validation. In general, we are removing all the spaces from the input using a regex.

2022-01-27 14:59 UTC, love-bhardwaj commented on test/jest/acceptance/snyk-apps/create-app.spec.ts
> +      // TODO: look for way to increase the line length
Have tried snapshot testing but got flaky tests with it. Presumably due to width of the screen is not always constant. So to took this approach to reduce the flakiness of the tests 🙂

2022-01-31 12:30 UTC, jahed-snyk requested changes
You haven't changed any dependencies right? If so, you'll need to revert package-lock.json. Happy to approve otherwise. I've left some other comments related to some duplication and improving input validation.

2022-01-31 12:46 UTC, jahed-snyk commented on src/cli/commands/apps/index.ts
> +    return `\n${readAppsHelpMarkdown(appsHelpFile)}`;
Instead of duplicating this logic, have you looked into re-using `commands/help`?

2022-01-31 12:46 UTC, jahed-snyk commented on src/lib/apps/create-app/index.ts
> +        .split(','),
We should validate each entry immediately after the split and fail on invalid ones. That should cover any commas in URLs.

Ideally to avoid conflicts like this, we should support passing the same flagging multiple times for array values. But we don't have that yet.

2022-01-31 12:46 UTC, jahed-snyk commented on src/lib/apps/create-app/index.ts
> +      snykAppScopes: options.scopes.replace(/\s+/g, '').split(','),
Should we validate these entrys to make sure they're correct scopes? Same question for the interactive format.

2022-01-31 12:46 UTC, jahed-snyk commented on test/jest/util/runCommand.ts
> +    setTimeout(() => {
Just to update with out of thread discussions. We'll be working on this in a future PR.

2022-01-31 13:22 UTC, love-bhardwaj commented on src/cli/commands/apps/index.ts
> +    return `\n${readAppsHelpMarkdown(appsHelpFile)}`;
Thanks, I will update that code to reuse the help command logic.

2022-01-31 13:41 UTC, love-bhardwaj commented on src/lib/apps/create-app/index.ts
> +      snykAppScopes: options.scopes.replace(/\s+/g, '').split(','),
Scopes validation could be a bit tricky at the moment. Since we are doing work in this area and they change frequently. So updating the list of valid scopes in the CLI code could be cumbersome. Ideally, you would want to fetch the valid scope list from API but this isn't available at the moment. So we are going ahead with whatever users provide and letting the API/Backend to the validations in this case.

We are actually validating the URL after splitting on `,` refer to the code [here](https://github.com/snyk/snyk/pull/2396/files#diff-aa08bc92fb0e1b39e7d207aa3b9e37cff15b2775d7bec3f4914a23984e0c77e9R34).

2022-01-31 15:56 UTC, jahed-snyk approved these changes
🎉

2022-01-31 15:59 UTC, jahed-snyk commented on src/lib/apps/utils.ts
> +}
Is this still needed?

2022-01-31 17:04 UTC, merged

2022-01-31 17:16 UTC, love-bhardwaj commented on src/lib/apps/utils.ts
> +}
There are a few minor improvements that need to be pushed. I will push in a separate PR 😄