test: migrate deduped-package-path to jest
snyk/snyk pull request #2406
Opened 2021-12-01 17:16 UTC by Avishagp

Migrate `deduped-package-path` from tap to jest.

2021-12-01 18:42 UTC, maxjeffos requested changes

2021-12-01 18:42 UTC, maxjeffos commented on test/jest/acceptance/deduped-package-patch.spec.ts
> +        stderr: expect.not.stringMatching(/snyk/gi),
maybe add a comment explaining why this assertion

2021-12-02 10:54 UTC, jahed-snyk approved these changes
Looks good. Might want to move the file to `acceptance/snyk-protect/` to make it clearer it's a `snyk protect` test.

2021-12-02 14:33 UTC, maxjeffos approved these changes

2021-12-02 14:50 UTC, merged