docs: update code command help
snyk/snyk pull request #2513
Opened 2022-01-04 02:16 UTC by awileysnyk

This file has all revisions through January 3, 2022, for review by the Hammer team. Question: For commands with the sub-command test, should the test command be explained the same as as the snyk test command: test a project for open source vulnerabilities and license issues? At this time, the code and iac commands say: test for any known issue. The container command says: test for any known vulnerabilities.

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-01-06 15:09 UTC, Avishagp commented on help/cli-commands/code.md
> +Specify the `<ORG_NAME>`, that is, an Organization in your Snyk account, to run Snyk commands tied to a specific organization. The Organization ID influences private test limits.
I thought the original sentence was more clear. Plus wanted to ask about the usage of `organization ID` instead of `organization name` at the end of the sentence.

2022-01-10 14:34 UTC, maxjeffos requested changes

2022-01-10 14:34 UTC, maxjeffos commented on help/cli-commands/code.md
> +Specify the `<ORG_NAME>`, that is, an Organization in your Snyk account, to run Snyk commands tied to a specific organization. The Organization ID influences private test limits.
There's a difference between organization name and organization ID. Your text @awileysnyk mentions them both, which is confusing. We should also make sure we know for sure:
- does it really support an org name? And if so is that the friendly org name or the code-y org name?
- does it support org ID?

For clarification, see picture

![image](https://user-images.githubusercontent.com/44034094/148783057-e472e112-8216-4da6-8120-65f3e15e7b4f.png)

2022-01-11 03:04 UTC, awileysnyk commented on help/cli-commands/code.md
> +Specify the `<ORG_NAME>`, that is, an Organization in your Snyk account, to run Snyk commands tied to a specific organization. The Organization ID influences private test limits.
Removed "that is, an Organization in your Snyk account." Changed to: The `<ORG_NAME>` influences private test limits. Organization ID may have come from conversation or another help file. Originally the text said "this influences," presumably meaning specifying the `<ORG_NAME>` or more simply, the `<ORG_NAME>`.

2022-01-11 03:06 UTC, awileysnyk commented on help/cli-commands/code.md
> +Specify the `<ORG_NAME>`, that is, an Organization in your Snyk account, to run Snyk commands tied to a specific organization. The Organization ID influences private test limits.
We thought this would be an organization name found in the user's Snyk account. Which form of the name would be found there?

2022-01-11 12:51 UTC, ArturSnyk commented
> should the test command be explained the same as as the snyk test command?
I don't think so, although both use the `test` Those two are not under the same execution path.
I would assume that with those changes when user will run `snyk code --help` the will be missing some common explanations (ones that snyk test has)

2022-01-12 04:01 UTC, awileysnyk commented
The intention is to have only the information that applies to the `snyk
code` command in the help for that command.

On Tue, Jan 11, 2022 at 7:52 AM Artur ***@***.***> wrote:

> should the test command be explained the same as as the snyk test command?
> I don't think so, although both use the test Those two are not under the
> same execution path.
> I would assume that with those changes when user will run snyk code --help
> the will be missing some common explanations (ones that snyk test has)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/snyk/snyk/pull/2513#issuecomment-1009934814>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWWRPDDYTFQGLQMF5RTFGELUVQRXNANCNFSM5LGMYVYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-12 15:40 UTC, Avishagp approved these changes

2022-01-12 16:45 UTC, merged