docs: update container command help
snyk/snyk pull request #2515
Opened 2022-01-04 02:34 UTC by awileysnyk

This file has all revisions through January 3, 2022, for review by the Hammer team. Question: For commands with the sub-command test, should the test command be explained the same as as the snyk test command: test a project for open source vulnerabilities and license issues? At this time, the code and iac commands say: test for any known issue. The container command says: test for any known vulnerabilities.

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-01-06 15:40 UTC, Avishagp approved these changes

2022-01-10 14:13 UTC, maxjeffos requested changes

2022-01-10 14:13 UTC, maxjeffos commented on help/cli-commands/container.md
>  Record the state of dependencies and any vulnerabilities on snyk.io.
Not quite right. It's more like "Capture the container image layers and dependencies and monitor for vulnerabilities in snyk.io".

2022-01-11 02:45 UTC, awileysnyk commented on help/cli-commands/container.md
>  Record the state of dependencies and any vulnerabilities on snyk.io.
Changed to "Capture the container image layers and dependencies and monitor for vulnerabilities on snyk.io."

2022-01-11 12:56 UTC, snaftaly commented on help/cli-commands/container.md
> +Allowed platforms are: `linux/amd64`, `linux/arm64`, `linux/riscv64`, `linux/ppc64le`, `linux/s390x`, `linux/386`, `linux/arm/v7`, or `linux/arm/v6`.
What do you think about using "Supported platforms" instead of "Allowed platforms"?

2022-01-12 04:03 UTC, awileysnyk commented
I have made a note of this and will go over a proposed change with the CLI
development team.

On Tue, Jan 11, 2022 at 7:56 AM Sharon Naftaly ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In help/cli-commands/container.md
> <https://github.com/snyk/snyk/pull/2515#discussion_r782118926>:
>
> >
> -#### `HTTPS_PROXY` and `HTTP_PROXY`
> +Allowed platforms are: `linux/amd64`, `linux/arm64`, `linux/riscv64`, `linux/ppc64le`, `linux/s390x`, `linux/386`, `linux/arm/v7`, or `linux/arm/v6`.
>
> What do you think about using "Supported platforms" instead of "Allowed
> platforms"?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/snyk/snyk/pull/2515#pullrequestreview-849129410>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWWRPDERI56EIBHLHNXPHZTUVQSJVANCNFSM5LGNRTXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-12 10:26 UTC, Avishagp commented on help/cli-commands/container.md
> +Allowed platforms are: `linux/amd64`, `linux/arm64`, `linux/riscv64`, `linux/ppc64le`, `linux/s390x`, `linux/386`, `linux/arm/v7`, or `linux/arm/v6`.
Changed 👍

2022-01-12 13:39 UTC, merged