docs: update log4shell command help
snyk/snyk pull request #2518
Opened 2022-01-04 03:12 UTC by awileysnyk

This file has all revisions through January 3, 2022, for review by the Hammer team.

2022-01-05 15:19 UTC, maxjeffos requested changes

2022-01-05 15:19 UTC, maxjeffos commented on help/cli-commands/log4shell.md
> +The log4shell command finds traces of the Log4J library that are affected by the Log4Shell vulnerability [CVE-2021-44228](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720), even
Backticks on `log4shell` (because it's a command)?

2022-01-05 15:19 UTC, maxjeffos commented on help/cli-commands/log4shell.md
> +To learn more about `snyk test --scan-all-unmanaged`, see the Maven options section of the [CLI reference](https://docs.snyk.io/features/snyk-cli/guides-for-our-cli/cli-reference).
This is a bit weird because their is no context for why you might care about `--scan-all-unmanaged`.

2022-01-11 01:54 UTC, awileysnyk commented on help/cli-commands/log4shell.md
> +The log4shell command finds traces of the Log4J library that are affected by the Log4Shell vulnerability [CVE-2021-44228](https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHELOGGINGLOG4J-2314720), even
Backticks added

2022-01-11 02:01 UTC, awileysnyk commented on help/cli-commands/log4shell.md
> +To learn more about `snyk test --scan-all-unmanaged`, see the Maven options section of the [CLI reference](https://docs.snyk.io/features/snyk-cli/guides-for-our-cli/cli-reference).
Changed "to learn more about" to "for information about" and note made to ask Jakub about this information.

2022-01-12 10:20 UTC, Avishagp approved these changes

2022-01-12 12:06 UTC, merged