docs: update monitor command help
snyk/snyk pull request #2519
Opened 2022-01-04 03:18 UTC by awileysnyk

This file has all revisions through January 3, 2022, for review by the Hammer team.

2022-01-05 02:33 UTC, maxjeffos requested changes

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
>  Can be used with --all-projects and --yarn-workspaces to indicate sub-directories and files to exclude. Must be comma separated.
Should we have backticks on `--all-projects` and `--yarn-workspaces`?

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
> +Continues to find all vulnerabilities, but potentially not all of the vulnerable paths.
Did you mean to use the past tense here?

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
> +Apply and use ignore rules from the snyk policies your dependencies; otherwise ignore rules in the dependencies are only shown as a suggestion.
Should we use uppercase `S` in Snyk?

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
> +Default: `<some>` (a few example paths shown).
I don't think you want the angle brackets: `<some>` -> `some`.

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
> +`<false>` is an alias for `<none>`.
Similar here

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
> +Manually pass a path to a snyk policy file.
Capitalization of Snyk

2022-01-05 02:33 UTC, maxjeffos commented on help/cli-commands/monitor.md
>  When monitoring a .NET project using NuGet `PackageReference` use the project name in project.assets.json, if found.
Backticks on the file name?

2022-01-11 01:36 UTC, awileysnyk commented on help/cli-commands/monitor.md
>  Can be used with --all-projects and --yarn-workspaces to indicate sub-directories and files to exclude. Must be comma separated.
This is done.

2022-01-11 01:38 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +Continues to find all vulnerabilities, but potentially not all of the vulnerable paths.
Changed to  but many not find all of the vulnerable paths

2022-01-11 01:40 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +Default: `<some>` (a few example paths shown).
Angle brackets removed for some, false, and none.

2022-01-11 01:43 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +Manually pass a path to a snyk policy file.
Changed to .snyk policy file

2022-01-11 01:46 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +Apply and use ignore rules from the snyk policies your dependencies; otherwise ignore rules in the dependencies are only shown as a suggestion.
For simplicity, uppercase S here

2022-01-11 01:47 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +`<false>` is an alias for `<none>`.
Angle brackets removed

2022-01-11 01:48 UTC, awileysnyk commented on help/cli-commands/monitor.md
> +`<false>` is an alias for `<none>`.
Angle brackets removed

2022-01-12 12:15 UTC, Avishagp approved these changes

2022-01-12 12:22 UTC, merged