feat:Refactor Docker-related functions in format-test-results.ts
snyk/snyk pull request #2523
Opened 2022-01-04 14:53 UTC by ChristinaDara

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?
Refactor the format-test-results script and split all docker related functions

#### Where should the reviewer start?
docker-format-test-results script

#### How should this be manually tested?

#### Any background context you want to provide?

The reason why moving this functions is the format-test-results.ts owned by Hammer team and each time we change any function related to docker we need Hammer approval. 
#### What are the relevant tickets?
https://snyksec.atlassian.net/browse/CAP-621

#### Screenshots

#### Additional questions

2022-01-05 09:43 UTC, shaninja reviewed
Good job refactoring those functions out!

Since our aim is to reduce our dependency on team Hammer when we want to make docker-specific changes, there's another change we should do: extract the tests. Because imagine that we'd want to make a change in the code, and as a result, the test would have to change. if we need Capsule approval for the code but Hammer approval for the test -- then we're still dependant on Hammer.

I know that the functions that you extracted aren't unit-tested directly (neither `groupVulnerabilities` nor `getDisplayedOutput`), but when looking at the tests for `displayResult`, there are test cases there that are distinct for dockers. So my ask is that you'd take `test/jest/unit/lib/formatters/test/display-result.spec.ts` and move all the docker-specific tests out of there and into a new fule.
Keep the new file in the same path (because it's supposed to mirror the code path, and `displayResult` is a function you haven't moved), and add that file also in the CODEOWNERS to have us as it's owners.

Thank you!!

2022-01-05 09:43 UTC, shaninja commented on .github/CODEOWNERS
> +/docker @snyk/hammer
question: is this change intentional?

2022-01-05 09:43 UTC, shaninja commented on .github/CODEOWNERS
> +src/lib/formatters/docker/docker-format-test-results.ts @snyk/capsule
@michael-c-snyk , @agatakrajewska , @RotemS -- do you think it might make sense for Capsule to own all of `src/lib/formatters/docker/`?

2022-01-05 09:45 UTC, ChristinaDara commented on .github/CODEOWNERS
> +/docker @snyk/hammer
I just removed a space

2022-01-05 09:49 UTC, shaninja commented on .github/CODEOWNERS
> +/docker @snyk/hammer
yes. I was asking if you intentionally did that, if there was a reason for it. Unfortunately, we don't have linting for CODEOWNER files, and I do not know if it expects a new line at the end (we could check).

(speaking from experience, because I once added a bad character in Registry's CODEOWNER file and it broke all the ownership without anyone noticing for days 😅 🙈 )

2022-01-05 10:01 UTC, ChristinaDara commented on .github/CODEOWNERS
> +/docker @snyk/hammer
when I added a line then the regression tests start failing so , I removed the space at the end removed the line and push then added the line again then I pushed it again

2022-01-05 10:16 UTC, shaninja commented on .github/CODEOWNERS
> +/docker @snyk/hammer
very strange 🤔  that feels unrelated. maybe hammer would have something to shed some light.

2022-01-05 10:23 UTC, ChristinaDara commented on .github/CODEOWNERS
> +src/lib/formatters/docker/docker-format-test-results.ts @snyk/capsule
I was thinking the same

2022-01-05 11:43 UTC, ChristinaDara commented on .github/CODEOWNERS
> +/docker @snyk/hammer
done with refactoring the test file

2022-01-05 15:36 UTC, RotemS commented on src/lib/formatters/docker/docker-format-test-results.ts
> +  if (options.showVulnPaths && !options.docker) {
If I understand correctly these results formatter is always container, so we don't need this?

2022-01-05 15:38 UTC, michael-c-snyk commented on .github/CODEOWNERS
> +/docker @snyk/hammer
If I'm reading the diff correctly, this PR seems to _add_ a space at the end of 51? What if that new space became a newline?

2022-01-05 15:40 UTC, ChristinaDara commented on .github/CODEOWNERS
> +/docker @snyk/hammer
I removed the space at the end and added 2 lines

2022-01-05 16:38 UTC, michael-c-snyk commented on .github/CODEOWNERS
> +/docker @snyk/hammer
![Screenshot 2022-01-05 at 16 35 04](https://user-images.githubusercontent.com/73909150/148254078-bd997ecc-4438-4743-b482-35b85456afc4.png)
Ignore me, I was confused by GH diff's view showing a space here, but pulled locally and it's not there

2022-01-05 16:40 UTC, michael-c-snyk commented on .github/CODEOWNERS
> +/docker @snyk/hammer
However my IDE shows the diff as being TWO blank lines being removed from the end 🤔 
![Screenshot 2022-01-05 at 16 40 28](https://user-images.githubusercontent.com/73909150/148254892-fd166ff0-6060-4ceb-8da1-101c3a537b1a.png)

2022-01-09 13:09 UTC, ChristinaDara commented on src/lib/formatters/docker/docker-format-test-results.ts
> +      map[curr.id] = {};
done , totally agree fixed that

2022-01-09 13:09 UTC, ChristinaDara commented on src/lib/formatters/docker/docker-format-test-results.ts
> +  return vulns.reduce((map, curr) => {
done , totally agree fixed that

2022-01-16 11:10 UTC, shaninja commented on src/lib/formatters/test/format-test-results.ts
>  export function groupVulnerabilities(
@ChristinaDara , can you please check if this function should also be removed? I see it in the new file, but it's also still here. probably a rebase error? and then I believe `metadataForVuln` should be removed as well.

2022-01-16 11:17 UTC, shaninja approved these changes

2022-01-16 11:18 UTC, shaninja commented
Approved after seeing that 2 of Rotem's requests were addressed. [The third one](https://github.com/snyk/snyk/pull/2523#discussion_r778908617)  needs to be investigated, and I believe it can be done and changed in a different PR, if needed (and also, we should now be sole code owners for said PR, so yay!)

2022-01-16 12:09 UTC, Avishagp commented on src/lib/formatters/test/format-test-results.ts
> -export function getDisplayedOutput(
Why were `getDisplayedOutput`, `groupVulnerabilities` and `metadataForVuln` moved to `docker-format-test-results`?
`getDisplayedOutput` uses all the other functions, and is used in `display-results.ts` where it's not specific only for docker scans.

2022-01-16 12:11 UTC, Avishagp commented on src/lib/formatters/test/display-result.ts
> -} from '../../../lib/formatters/test/format-test-results';
See my comment on `format-test-results.ts`. `getDisplayedOutput` function is not only used for docker, it's not right to move it to a docker specific file.

2022-01-16 13:00 UTC, Avishagp requested changes
getDisplayedOutput function is not only used for docker, it's not right to move it to a docker specific file

2022-01-18 11:07 UTC, closed without merging