refactor: Change getVersion() from async to sync
snyk/snyk pull request #2533
Opened 2022-01-10 12:26 UTC by YairZ101

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-01-10 16:48 UTC, anthogez reviewed
I understand your point of view regarding this being a refactor, although we are changing the flow from "async" to "sync" would suggest `feat` rather than `refactor`

2022-01-11 13:53 UTC, YairZ101 commented
> I understand your point of view regarding this being a refactor, although we are changing the flow from "async" to "sync" would suggest `feat` rather than `refactor`

Changed it to `feat`.
Other than that, do you agree / disagree with the change? I'm looking to get some feedback :)

2022-01-11 16:23 UTC, jahed-snyk requested changes
As I understand it, this change is for dev convenience, right? To me, we shouldn't be removing async code only to avoid having to write async code. NodeJS is built around async so we should be designing for it. Sync code will cause perf issues and block event loops. So we should be reducing sync flows and optimising for async flows. For example, that `fs.readFileSync` for the `package.json` should be `fs.readFile`.

If an async `getVersion` is causing inconveniences for devs, we should look into improving the way it's retrieved rather than making it synchronous. For example, I noticed we are retrieving it on every HTTP request. A filesystem read and/or 3 git executions on every HTTP call. That's excessive and it should really be gated, retrieve once, stored and reused. This will allow other flows beyond the gate to retrieve it synchronously (since it's just stored state) and solve the dev inconvenience.

---

Side note, I don't think the git-related logic after the version check is ever executed. As far as I know, the package.json version is never 0.0.0 so that branch will always return early.

2022-01-12 11:11 UTC, YairZ101 commented
> If an async `getVersion` is causing inconveniences for devs, we should look into improving the way it's retrieved rather than making it synchronous. For example, I noticed we are retrieving it on every HTTP request. A filesystem read and/or 3 git executions on every HTTP call. That's excessive and it should really be gated, retrieve once, stored and reused. This will allow other flows beyond the gate to retrieve it synchronously (since it's just stored state) and solve the dev inconvenience.

What is your opinion on saving the version in the config?



> Side note, I don't think the git-related logic after the version check is ever executed. As far as I know, the package.json version is never 0.0.0 so that branch will always return early.

how can I verify that? if that's the case we can simply delete this part...

2022-01-12 22:38 UTC, jahed-snyk commented
>how can I verify that? if that's the case we can simply delete this part...

Delete it and see which tests fail, if any. It looks like a dev thing so I doubt we need it. If we can delete it then I think it's fine to change getVersion to sync since that's what it will be without the exec stuff.

>What is your opinion on saving the version in the config?

Config as in `config.ts`? That supports user overrides so I don't think it belongs there but it can be something similar. There are a number of runtime details which Snyk CLI recalculates constantly which could be stored. I'll backlog this issue on Hammer's end as the whole "reading a file on every HTTP call" definitely needs fixing.

2022-01-13 16:05 UTC, YairZ101 commented
> Delete it and see which tests fail, if any. It looks like a dev thing so I doubt we need it. If we can delete it then I think it's fine to change getVersion to sync since that's what it will be without the exec stuff.

Deleted it and it looks good, from your perspective we can merge this change?

2022-01-13 17:43 UTC, jahed-snyk approved these changes
I think we can simplify it a little bit more. But other than that, looks good. Thanks for bring this up!

2022-01-13 17:43 UTC, jahed-snyk commented on src/lib/version.ts
> +  return 'unknown';
We can remove the "if" and just return version I think. We'll always have package.json and a version. "0.0.0" can be considered "unknown" implictly if it ever does show up.

2022-01-16 15:52 UTC, YairZ101 commented on src/lib/version.ts
> +  return 'unknown';
Done, thank you for all your insights during this review process! :)

2022-01-16 15:52 UTC, merged