[CFG-1484] Add a static help message for snyk iac drift scan
snyk/snyk pull request #2735
Opened 2022-02-07 14:20 UTC by sundowndev

- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

Following #2634. This PR adds a help message for the `snyk iac drift scan` command.

#### Where should the reviewer start?

TBA

#### How should this be manually tested?

TBA

#### Any background context you want to provide?

TBA

#### What are the relevant tickets?

- https://snyksec.atlassian.net/browse/CFG-1484
- https://github.com/snyk/snyk/pull/2634

#### Screenshots

![cli](https://user-images.githubusercontent.com/16480203/152805308-5e8ade55-285f-4e9a-9d19-8052eb03c808.png)

2022-02-14 14:13 UTC, craigfurman commented
Just a note for others - we likely don't want to merge this. We want separate help pages for the various iac subcommands, which will involve changing the way the CLI handles help.

2022-02-17 10:00 UTC, craigfurman requested changes
This works, which is great 🎊 

I have some minor notes, but after that it'll be ready to merge from my PoV at least. We'll still need hammer's review.

2022-02-17 10:00 UTC, craigfurman commented on test/jest/unit/cli/commands/help/help.spec.ts
> +describe('getHelpFilePath', () => {
can we include some tests around top-level commands like `test`? Maybe just one (test) is good enough, as an example.

Also, when we were planning this out, I thought the plan was to extract the getHelpFilePath and backfill tests in one commit, _then_ extend it with the drift-supporting code. That way, with passing tests on the first commit, we'd have been more confident there were no regressions.

2022-02-17 11:58 UTC, sundowndev commented on test/jest/unit/cli/commands/help/help.spec.ts
> +describe('getHelpFilePath', () => {
> thought the plan was to extract the getHelpFilePath and backfill tests in one commit, then extend it with the drift-supporting code

You're right, I did added tests before refactoring the help command but then forgot to make a commit. Will rewrite the git history.

2022-02-17 17:07 UTC, craigfurman commented on src/cli/commands/help/index.ts
> +  return path.resolve(process.cwd(), 'help/cli-commands', `${item}.md`);
I hadn't spotted this, but @sundowndev found that this is what was breaking the tests. I'm pretty sure that if we'd shipped this, it would have broken the help for everyone who ran `snyk` outside of the package's own distribution directory 😉 

We'll put this into ready mode when we've fixed this up, for a proper review.

2022-02-18 09:03 UTC, neonnoon approved these changes
Approved for nebula-owned test file changes. Let me know if I should have a closer look.

2022-02-18 09:24 UTC, craigfurman commented on src/cli/commands/help/index.ts
> +  return path.resolve(process.cwd(), 'help/cli-commands', `${item}.md`);
Looks like this is fixed now

2022-02-18 09:29 UTC, craigfurman commented on src/cli/commands/help/index.ts
> +  if (filepath.indexOf('dist') > -1) {
I think we'd appreciate Hammer's advice for how to be able to do what we're doing here - to have a meaningfully unit-testable getHelpFilePath funciton that returns a relative path to help files, while not breaking the distribution 😬

2022-02-19 05:40 UTC, sundowndev commented on src/cli/commands/help/index.ts
> +  if (filepath.indexOf('dist') > -1) {
FYI, I've pushed a different approach in branch `docs/drift_help_message2` which avoid using fuzzy search and doesn't impact existing commands. I'm less confident with it, as it brings technical debt, but it may be a good first step.

2022-02-21 09:26 UTC, craigfurman commented on src/cli/commands/help/index.ts
> +  if (filepath.indexOf('dist') > -1) {
Let's let hammer decide

2022-02-22 11:31 UTC, craigfurman commented
Let's supersede this with https://github.com/snyk/snyk/pull/2780. Will close this if that gets merged 🙏

2022-02-23 13:47 UTC, craigfurman commented
Superseded by https://github.com/snyk/snyk/pull/2780

2022-02-23 13:47 UTC, closed without merging