feat: add org name to snyk code test [NEBULA-195]
snyk/snyk pull request #2764
Opened 2022-02-17 09:58 UTC by patricia-v

- [ ] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules

#### What does this PR do?

#### Where should the reviewer start?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant tickets?

#### Screenshots

#### Additional questions

2022-02-20 14:46 UTC, ArturSnyk commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
I would not mutate the `option.org` object. this might cause some side effects that we don't expect. Instead, we can in every place we check for `options.org` use `options.org || sastSettings.org`

2022-02-20 14:47 UTC, ArturSnyk commented
[suggestion] let's also add tests for this case?

2022-02-21 07:40 UTC, patricia-v commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
I agree that changing `option.org` is not the best thing. However, to solve this problem we will need the new org in the `meta` const in the next line. I didn't want to change how `getMeta` is called, so what would be the best solution here? I would have to change the arguments of `getMeta` to either include the `options.org || sastSettings.org` (or a new const with this result), or just the `sastSettings/sastSettings.org`. Do you think this is a good solution, or do I need a new approach here?

2022-02-21 11:39 UTC, pkey requested changes
Agree with @ArturSnyk's comment, let's have a test to make sure we prevent this issue in the future.

2022-02-21 11:39 UTC, pkey commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
@ArturSnyk I think this is not a bad approach. It's basically saying - if no `org` defined in options let that `org` be the default one. Also, `getMeta` is the only consumer of options and all it does is extract the relevant information.

2022-02-21 11:39 UTC, pkey commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
@patricia-v have you looked at how other `snyk` commands assign default `org`? Like `snyk test`. As far as I know, this issue is handled there so maybe we can actually use that solution?

2022-02-21 12:19 UTC, patricia-v commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
@pkey I have, it is done in a very different way, even in the formatting of the output in the CLI. `snyk test` requests from a few APIs that `snyk code test` doesn't, and one of those returns the org. [Somewhere down the line](https://github.com/snyk/snyk/blob/66f09c231f8fa0326bc06c679da045832d5a59e0/src/lib/formatters/format-test-meta.ts#L17) the response of this request is used as an argument to format the output, including the `Organization`.

In this case I think it would be similar to passing the `sastSettings` in the arguments of `getMeta`.

2022-02-21 12:21 UTC, pkey commented on src/lib/plugins/sast/index.ts
> +        options.org = sastSettings.org;
@patricia-v sounds good then.

2022-02-21 12:22 UTC, pkey commented
@patricia-v let me know if you get stuck with the tests we can look together!

2022-02-23 14:27 UTC, pkey approved these changes

2022-02-23 17:13 UTC, merged